PrismLibrary/Prism

Source/Prism/Mvvm/ViewModelLocationProvider.cs, Source/Wpf/Prism.Wpf.Tests/Mocks/Views/MockView.cs, Source/Wpf/Prism.Wpf.Tests/Mvvm/ViewModelLocatorFixture.cs, Source/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
Fix issue #12: Improve ViewModelLocator ViewModel type name convention assumptions
=> Improve ViewModelLocator ViewModel type name convention assumptions

Source/PrismLibrary_Tests.sln, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/BootstrapperFixtureBase.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/DependantA.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/DependantB.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/MockLoggerAdapter.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/MockModuleLoader.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/MockRegionManager.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/MockService.cs, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Prism.IocContainer.Wpf.Tests.Support.csproj, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj, Source/Wpf/Prism.Unity.Wpf.Tests/UnityBootstrapperFixture.cs, Source/Wpf/Prism.Unity.Wpf.Tests/UnityBootstrapperNullContainerFixture.cs, Source/Wpf/Prism.Unity.Wpf.Tests/UnityBootstrapperNullLoggerFixture.cs, Source/Wpf/Prism.Unity.Wpf.Tests/UnityBootstrapperNullModuleCatalogFixture.cs, Source/Wpf/Prism.Unity.Wpf.Tests/UnityContainerExtensionFixture.cs
Currently named the shared library Prism.IocContainer.Wpf.Tests.Support, similar to the existing library Prism.Mef.Wpf.Tests.Support. Naming is open for discussion.
=> Moved BootstrapperFixtureBase and mocks, fixes #18

Samples/Windows10/HelloWorld/HelloWorld.sln, Samples/Windows10/HelloWorld/HelloWorld/App.xaml.cs, Samples/Windows10/HelloWorld/HelloWorld/Converter/BooleanToVisibilityConverter.cs, Samples/Windows10/HelloWorld/HelloWorld/HelloWorld.csproj, Samples/Windows10/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs, Samples/Windows10/HelloWorld/HelloWorld/Views/MainPage.xaml, Source/Windows10/Prism.Unity.Windows/PrismUnityApplication.cs, Source/Windows10/Prism.Windows/Prism.Windows.csproj, Source/Windows10/Prism.Windows/PrismApplication.cs
Made PrismApplication methods async as they should be (and were in the
Converged branch in UWP).
Added the SettingsFlyout with Win10 contracts, but noted that the
SettingsPane class got an Obsolete attribute in the latest SDK, to be
checked how this goes forward.
=> PrismApplication methods async and SettingsFlyout

Source/Wpf/Prism.Wpf.Tests/Interactivity/PopupWindowActionFixture.cs, Source/Wpf/Prism.Wpf/Interactivity/DefaultPopupWindows/DefaultConfirmationWindow.xaml, Source/Wpf/Prism.Wpf/Interactivity/DefaultPopupWindows/DefaultNotificationWindow.xaml, Source/Wpf/Prism.Wpf/Interactivity/DefaultPopupWindows/DefaultWindow.xaml, Source/Wpf/Prism.Wpf/Interactivity/DefaultPopupWindows/DefaultWindow.xaml.cs, Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs, Source/Wpf/Prism.Wpf/Prism.Wpf.csproj
PopupWindowAction now can receive a `Style` through it's `WindowStyle` property. The `Style` should target a `Window`.
All `Window's` customizations where moved to `xaml`.
=> PopupWindowAction can receive a Style for it's Window.

Samples/Windows10/HelloWorld/HelloWorld/App.xaml.cs, Source/Windows10/Prism.Windows/PrismApplication.cs
Removed old HardwareButton code as this is part of DeviceGestureService now.
The problem with PrismApplication.OnLaunched is that it always assumes that the Window.Current.Content is a Frame. This is not the case when for example implementing the SplitView navigation pattern. When using the SplitView navigation pattern the Window.Current.Content will be a Page with a SplitView and SplitView.Content = rootFrame.
The CreateShell method is similar to the WPF version and adds support for other root elements, for example a Page. In the CreateShell method you are then in full control of the rootFrame and where it should be placed.
I'm not sure what's best though: abstract or virtual. CreateShell has the rootFrame as param which can then be returned as shown in the HelloWorld sample.
Question: …
=> [UWP] PrismApplication - CreateShell and Cleanup

Source/Windows10/Prism.Windows/PrismApplication.cs
SessionStateService, NavigationService, DeviceGestureService can now be injected via the new virtual calls. Added optional OnSuspendingApplicationAsync which is called before the general suspending calls. (You could already overwrite Shell if required so I didn't touch that.)
=> Implemented some proposed changes from #146, added OnSuspendingApplicationAsync

Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs, Source/Xamarin/Prism.Unity.Forms/UnityBootstrapper.cs
For the PageDialogService to work properly it needs to know the current page. This fix expands on the current solution for the NavigationService to the PageDialogService.
fixes #254
=> Inject current page in pageDialogService

Source/Prism/Commands/DelegateCommandBase.cs, Source/Prism/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Autofac.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Mef.Wpf/Modularity/ModuleExportAttribute.cs, Source/Wpf/Prism.Mef.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Ninject.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.StructureMap.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Unity.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Unity.Wpf/UnityBootstrapper.cs, Source/Wpf/Prism.Unity.Wpf/UnityBootstrapperExtension.cs, Source/Wpf/Prism.Unity.Wpf/UnityContainerHelper.cs, Source/Wpf/Prism.Unity.Wpf/UnityServiceLocatorAdapter.cs
Mark the core and WPF assemblies as CLS Compliant.
There are only a few things in the assemblies that aren't CLSCompliant, so I've marked the exceptions.
This should make using Prism from a solution that is marked as CLSCompliant less painful - and has no impact on other with non compliant (or not explicitly stated compliance).
=> Add CLSCompliance to Prism and Prism.WPF assemblies

Source/Windows10/Prism.Windows/PrismApplication.cs
Not all apps need to handle all forms of activation. Also refactored common code from OnActivateApplication and OnLaunchApplication to private method.
=> Made OnActivateAppAsync virtual instead of abstract

Source/Windows10/Prism.Autofac.Windows/PrismAutofacApplication.cs, Source/Windows10/Prism.Unity.Windows/PrismUnityApplication.cs, Source/Windows10/Prism.Windows.Tests/DeviceGestureServiceFixture.cs, Source/Windows10/Prism.Windows.Tests/FrameFacadeAdapterFixture.cs, Source/Windows10/Prism.Windows.Tests/FrameNavigationServiceFixture.cs, Source/Windows10/Prism.Windows.Tests/Prism.Windows.Tests.csproj, Source/Windows10/Prism.Windows.Tests/Utilities/DispatcherHelper.cs, Source/Windows10/Prism.Windows.Tests/ViewModelLocatorFixture.cs, Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs, Source/Windows10/Prism.Windows/AppModel/IDeviceGestureService.cs, Source/Windows10/Prism.Windows/Navigation/FrameFacadeAdapter.cs, Source/Windows10/Prism.Windows/Navigation/FrameNavigationService.cs, Source/Windows10/Prism.Windows/Navigation/IFrameFacade.cs, Source/Windows10/Prism.Windows/Navigation/NavigationStateChangedEvent.cs, Source/Windows10/Prism.Windows/Navigation/NavigationStateChangedEventArgs.cs, Source/Windows10/Prism.Windows/Prism.Windows.csproj, Source/Windows10/Prism.Windows/PrismApplication.cs
Per discussion with @briannoyes on this [thread](https://github.com/PrismLibrary/Prism/issues/67#issuecomment-151216271), I've refactored the title bar back button handling such that DeviceGestureService handles toggling the visibility of the back button by listening for navigation Pub/Sub events from the FrameFacadeAdapter.
=> Refactored title bar back button handling so it's always accurate

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
The popup window is now centered above the associated object, clamped to the desktop work area. Also, fixed screen coordinates vs device independent pixels. Tested on both 100% and 125% DPI.
=> CenterOverAssociatedObject formula fixed

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
With multiple monitors, the X and Y coordinates of the view can be negative if we are initiating the call from the left of the PrimaryScreen of above it.
I tested this on a 2 monitors setup. My main screen is a 4k set at 175% and the laptop screen is UHD set at 150 %.
=> Update PopupWindowAction for multiple screens

Samples/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Samples/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
When using an absolute URI the entire navigation stack will be replaced no matter where you are currently in the application.
=> Changed absolute URI behavior

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
When a page cannot be created (null), then an exception is thrown to inform the developer to register the page for navigation.
=> throw exception for null page in navigation service

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
When navigating form a MasterDetailPage in which the Detail is the same type as the navigation target, we need to close the drawer. Fixes issue #388
=> Close drawer on MasterDetailPage navigation

Source/Wpf/Prism.Wpf/Regions/Behaviors/RegionMemberLifetimeBehavior.cs
Added a conditional check to see if the view being removed exists in the region before trying to remove it.  This can happen if using the IRegionMemberLifetime interface or attribute and manually removing views from a region by calling Region.Remove.
=> RegionMemberLifetimeBehavior - conditional check for removing views

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
In my tests GetWindow(AssociatedObject) was more reliable than GetWindow(this), but I was not sure I could not prove it definitely.  So I compromised and suggested a coalesce.
=> GetWindow(this) can return null

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
removed the logic in the PageNavigationService that tried to
automatically detect if a deep link was being used and turned animation
off.  This causes unexpected behavior in some scenario and also disables
the ability to control the animation with the animated parameter which
is not a good API design.
=> removed deep link animation logic

Extensibility/TemplatePack/ProjectTemplates/CSharp/Wpf/PrismModule/Module.cs, Extensibility/TemplatePack/ProjectTemplates/CSharp/Wpf/PrismModule/PrismModule.vstemplate, Extensibility/TemplatePack/ProjectTemplates/CSharp/Wpf/PrismModule/ProjectTemplate.csproj, Extensibility/TemplatePack/TemplatePack.sln, Extensibility/TemplatePack/TemplatePack/TemplatePack.csproj, Extensibility/TemplatePack/TemplatePack/source.extension.vsixmanifest, Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/ExtractModuleFileNameWizard.cs, Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/Prism.VisualStudio.Wizards.csproj, Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/Properties/AssemblyInfo.cs
added a wizard to rename the module class in the Prism Module ProjectTemplate to support more complex project names such as "Prism.Modules.Admin".  This will result in a class being call AdminModule
=> Module Rename Wizard

Extensibility/TemplatePack/VsPackages/ConfigModuleEditor/ConfigModuleEditorPane.cs
when an exception is thrown due to a failure in loading the projects, a message is shown to the user and the editor no longer crashes.
=> Module Editor error handling

Source/Prism.Tests/Events/BackgroundEventSubscriptionFixture.cs, Source/Prism.Tests/Events/DispatcherEventSubscriptionFixture.cs, Source/Prism.Tests/Events/EventSubscriptionFixture.cs, Source/Prism.Tests/Events/PubSubEventFixture.cs, Source/Prism/Events/BackgroundEventSubscription.cs, Source/Prism/Events/DispatcherEventSubscription.cs, Source/Prism/Events/EventSubscription.cs, Source/Prism/Events/PubSubEvent.cs
The non-generic version of the PubSubEvent does not have an option for a filter predicate.
Fix for Issue #482
=> Non-generic PubSubEvent

Documentation/WPF/10-InitializingPrismApplications.md
In documentation, fixed some characters like `<` and `>` are escaped to `&lt;` and `&gt;` in code segments.
=> Fixed some HTML escape characters in code fields.

Source/Wpf/Prism.Ninject.Wpf/NinjectExtensions.cs
Add extensions for RegisterTypeForNavigation to IKernel  and Ninjectmodule, similar to the method available on Container for Unity/MEF.
(in response to logged issue #534)
=> Add RegisterTypeForNavigation to IKernel and NinjectModule

Source/Xamarin/Prism.Forms.Tests/Mocks/ApplicationProviderMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/PageDialogServiceMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationServiceMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Forms.Tests/Services/PageDialogServiceFixture.cs, Source/Xamarin/Prism.Forms/Common/ApplicationProvider.cs, Source/Xamarin/Prism.Forms/Common/IApplicationProvider.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs, Source/Xamarin/Prism.Ninject.Forms/Navigation/NinjectNavigationService.cs, Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs, Source/Xamarin/Prism.Unity.Forms/Navigation/UnityPageNavigationService.cs, Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
To help keep Prism for XF testable, I abstracted away the dependency on
Application.Current (which isn't testable) and replaced it with
IApplicationProvider.
=> Added IApplicationProvider

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/SomeOtherViewModel.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MainPage.xaml, Source/Prism.Tests/Mvvm/ViewModelLocationProviderFixture.cs, Source/Prism/Mvvm/ViewModelLocationProvider.cs
The ViewModelLocationProvider has a new Register method which allows a developer to decide which ViewModel to use based on a VM type.  This means that the conventions can be bypassed, and the dev can supply which ViewModel to use instead.
=> Extended ViewModelLocator to override conventions

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs, Source/Xamarin/Prism.Ninject.Forms/Navigation/NinjectPageNavigationService.cs, Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj, Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs, Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
made the INavigationService methods virtual, and added a named registration for the service so that it is easier to override Prism's implementation.
=> made the INavigationService more extensible

Source/Xamarin/Prism.Forms.Tests/Mocks/ViewModels/ViewModelBase.cs, Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs, Source/Xamarin/Prism.Ninject.Forms/NinjectExtensions.cs, Source/Xamarin/Prism.Unity.Forms/UnityExtensions.cs
Updates Generic Type names across DI Navigation extensions, and INavigationService so that generic type is either TView or TViewModel so as to be more descriptive for developers. Requires TViewModel to derive from BindableBase.
=> View model navigation contraints

Source/Windows10/Prism.Autofac.Windows/Prism.Autofac.Windows.csproj, Source/Windows10/Prism.SimpleInjector.Windows/Prism.SimpleInjector.Windows.csproj, Source/Windows10/Prism.Unity.Windows/Prism.Unity.Windows.csproj, Source/Windows10/Prism.Windows.Tests/Prism.Windows.Tests.csproj, Source/Windows10/Prism.Windows/Prism.Windows.csproj
I would like to be able to build prism without having old sdk installed. I don't know any reason to use outdated 10.0.10240.0 and I guess it's ok to increase target version.
=> Update target platform for Universal Windows projects

Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationServiceMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs, Source/Xamarin/Prism.Ninject.Forms/Navigation/NinjectPageNavigationService.cs, Source/Xamarin/Prism.Unity.Forms/Navigation/UnityPageNavigationService.cs
Added ILoggerFacade to PageNavigationService. Logging exceptions thrown in CreatePageFromSegment. Updated Tests. PR for issue #576
=> Add logging for Failed Navigation

Source/Wpf/Prism.Unity.Wpf/UnityExtensions.cs, Source/Xamarin/Prism.Unity.Forms/UnityExtensions.cs
The Unity pattern for type registration passes back the container to allow chaining type registration. This update will allow the same type of chaining.
```cs
Container.RegisterTypeForNavigation<ViewA>()
.RegisterInstance( someInstance )
.RegisterType<IFoo, Foo>()
.RegisterTypeForNavigation<ViewB>();
```
This update only targets Unity as Ninject follows a different pattern for type registrations.
=> Updated XF UnityExtensions to follow Type Registration Conventions

Source/Prism.Tests/Mvvm/CompositeCommandFixture.cs, Source/Prism.Tests/Mvvm/DelegateCommandFixture.cs, Source/Prism/Commands/DelegateCommandBase.cs
now DelegateCommand uses the SynchronizationContext to post the CanExecuteChange event to the proper thread.  Fixes issues #299, #322, and #608
=> DelegateCommand.RaiseCanExecuteChanged on UI Thread

Source/Xamarin/Prism.Unity.Forms/UnityExtensions.cs
Unity returns the container after registration for chaining.
=> Following Unity conventions for RegisterType()

Extensibility/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio/ProjectTemplates/PrismUnityApp/PrismUnityApp.xpt.xml, Extensibility/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio/Properties/AddinInfo.cs
Fixed the project template for Xamarin Studio  6.0.  There was a breaking change with XS 6.0 where the portable project type changed from PortableDotNet to C#PortableLibrary
=> fixed project type for XS 6.0

Source/Wpf/Prism.Wpf/Regions/RegionManager.cs
Fix for #658.
There are no unit tests for RegionManager.RequestNavigate at all, but that seems to be a subject for another ticket - #660.
=> Fix for RegionManager.RequestNavigate error handling

Source/Xamarin/Prism.Forms.Tests/Common/UriParsingHelperFixture.cs, Source/Xamarin/Prism.Forms/Common/UriParsingHelper.cs
Simplified method to utilize StringSplitOptions.RemoveEmptyEntries. Added test to ensure empty entries aren't added to the segments queue.
=> Simplified method GetUriSegments

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
In replace of #709 
Prism' PopupWindowAction was created based on Damian Cherubini's [PopupWindowAction: using custom views instead of windows in WPF and Prism](http://southworks.com/blog/2012/05/24/popupwindowaction-using-custom-views-instead-of-windows-in-wpf-and-prism/).
The comment was valid in Cherubini's version, but Prism' version does not have this functionality: it does not set RegionManager.
=> Remove invalid comment

Source/Xamarin/Prism.Forms/Mvvm/ViewModelLocator.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
First attempt at autosetting VML.AutowireViewModel propery to true.  This makes using Prism even easier as you no longer have to worry about doing this manually.  This does make this an opt-out feature.
=> Autoset AutowireViewModel

Source/Windows10/Prism.Windows/PrismApplication.cs
This fixes a bug in https://github.com/PrismLibrary/Prism/issues/795, allowing `OnNavigatedTo` to be called when the app is resuming from an in-memory resume (app has not been terminated yet).
=> Fix resume methods on app resume

Source/Windows10/Prism.Windows.Tests/Mocks/MockSessionStateService.cs, Source/Windows10/Prism.Windows/AppModel/ISessionStateService.cs, Source/Windows10/Prism.Windows/AppModel/SessionStateService.cs, Source/Windows10/Prism.Windows/PrismApplication.cs
Picking this back up from #539.
This pull request addresses #281 Prism.Windows should provide a hook for the application to prevent restoring app state.
Adding an override to PrismApplication to allow the app to provide custom logic that determines whether the app should restore state from a previous session.
=> #281 Adding an override to provide custom logic for determing when to restore.

Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs
Reverts PrismLibrary/Prism#860.  This PR broke an Autofac test
```
[Fact]
public async Task Navigate_Key()
{
var app = new PrismApplicationMock();
var navigationService = ResolveAndSetRootPage(app);
await navigationService.NavigateAsync("view");
var rootPage = ((IPageAware)navigationService).Page;
Assert.True(rootPage.Navigation.ModalStack.Count == 1);
Assert.IsType(typeof(ViewMock), rootPage.Navigation.ModalStack[0]);
}
```
=> Revert "Autoresolve types with Autofac"

Source/Wpf/Prism.Wpf.Tests/Modularity/DirectoryModuleCatalogFixture.Desktop.cs, Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.Desktop.cs, Source/Wpf/Prism.Wpf/Modularity/FileModuleTypeLoader.Desktop.cs
Fixes issue #926 per https://connect.microsoft.com/VisualStudio/feedback/details/750678/codebase-does-not-correctly-escape-character
- Use Assembly.EscapedCodeBase instead of Assembly.CodeBase
=> Use EscapedCodeBase to correctly handle special characters

Source/Xamarin/Prism.Forms.Tests/Common/UriParsingHelperFixture.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Common/UriParsingHelper.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Fixes issue #932 .
- Add Parse method to UriParsingHelper.
- Update NavigateAsync on PageNavigationService.
- Add unit test for absolute navigations.
=> Fix absolute navigation of UWP

docs/Xamarin-Forms/6-EventToCommandBehavior.md
Fixes bad docs as pointed out on [StackOverflow](http://stackoverflow.com/questions/41999607/eventtocommandbehavior-namespace-prefix-b-is-not-defined)
=> fix improper namespaces in docs

Source/Xamarin/Prism.Forms.Tests/Mocks/IPageNavigationEventRecordable.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationServiceMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/ViewModels/ViewModelBase.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/CarouselPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/ContentPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/MasterDetailPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/NavigationPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/TabbedPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Fixes issue #862 .
I'm sorry. 
I typed "IPageNavigationEventRecordable" as "IPageNavigationEventRecodable".
In addition, PageNavigationServiceMock#CreatePage has been modified to be smart with Page Utilities#InvokeViewAndViewModelAction.
- Fixed from IPageNavigationEventRecodable to IPageNavigationEventRecordable
- Fixed PageNavigationServiceMock#CreatePage to use PageUtilities
=> Fixed typo for IPageNavigationEventRecordable

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs
Fixes issue #432  .
Instead of 
```xaml
<prism:InteractionRequestTrigger SourceObject="{Binding CustomPopupRequest}">
<prism:PopupWindowAction IsModal="True" CenterOverAssociatedObject="True">
<prism:PopupWindowAction.WindowContent>
<views:CustomPopupView />
</prism:PopupWindowAction.WindowContent>
</prism:PopupWindowAction>
</prism:InteractionRequestTrigger>
``` 
you can use
```xaml
<prism:InteractionRequestTrigger SourceObject="{Binding CustomPopupRequest}">
<prism:PopupWindowAction IsModal="True" CenterOverAssociatedObject="True" 
WindowContentType="{x:Type views:CustomPopupView}"/>
</prism:InteractionRequestTrigger>
```
=> WindowContentType property added

Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Ensures that the `PrismApplication.NavigationService` is created after registrations are complete so that any custom implementation of `INavigationService` is resolved and ready for use in `OnInitialized` rather than the default container implementation.
=> Enable Custom NavigationService Creation

Source/Prism.Tests/Commands/DelegateCommandFixture.cs, Source/Prism/Commands/DelegateCommandBase.cs
=> Raise CanExecuteChanged on PropertyChange empty

Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs, Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs, Source/Xamarin/Prism.Forms/AppModel/ApplicationStore.cs, Source/Xamarin/Prism.Forms/AppModel/IApplicationStore.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs, Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
Adding `IApplicationStore` to expose `Application.Properties` & `Applicaiton.SavePropertiesAsync()` to be consumed in a ViewModel without exposing properties that a ViewModel probably shouldn't have access to like `Application.MainPage`
=> Exposes `Application.Properties` and `Application.SavePropertiesAsync()`

Source/Xamarin/Prism.Forms.Tests/Services/PageDialogServiceFixture.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Forms/Services/PageDialogService/ActionSheetButton.cs, Source/Xamarin/Prism.Forms/Services/PageDialogService/ActionSheetButtonBase.cs, Source/Xamarin/Prism.Forms/Services/PageDialogService/ActionSheetButton{T}.cs, Source/Xamarin/Prism.Forms/Services/PageDialogService/IActionSheetButton.cs, Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs
Replaces PR #837 for issue #836 
- Adds support for the use of injecting a generic parameter
- Deprecates the use of `ICommand`
- Introduces support for directly using an `Action` or `Action<T>`
=> ActionSheetButton Enhancements

Source/Windows10/Prism.Windows/PrismApplication.cs
Not a fix for any specific issue. Just an addiction for #867.
Skip executing if GoBackEvent already  handled
=> Check for e.Handled inside PrismApplication.OnGoBackRequested

Source/Xamarin/Prism.Forms.Tests/Navigation/NavigationParametersFixture.cs, Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs
Problem
===
I want to retrieve values from NavigationParameters that are of a common base type.
This is not possible since there is an error thrown indicating that the type must implement IConvertible.
Since the type I passed inherits the type of the generic parameter T there is no need to implement IConvertible.
What is changed
===
I changed the code so that if the type inherits the generic parameter T then the item is returned.
NavigationParameters does now allow to retrieve values if T is a parent of the item.
NavigationParameters.GetValue<T>
NavigationParameters.GetValues<T>
NavigationParameters.TryGetValue<T>
Fixes issue #1008 .
- 
public class Test : ICustomInterface{}
NavigationParameters np = …
=> NavigationParameters does now allow to specify a base type as generic parameter T

Source/Windows10/Prism.Windows/PrismApplication.cs
Opening a prism uwp app by share target, results in a hanging app (You only see the splash screen, no view will be loaded)
This is behavior is caused by not calling InitializeShell.
Fixes issue # .
Override OnShareTargetActivated and call OnActivated to initiate the "bootstrapping" process of prism.
This issue and PR is related to #943
=> Handle share activation and init boostraping

Source/Windows10/Prism.Windows/PrismApplication.cs
Fixes issue #853.
Removed Exit() call for devices with hardware buttons.
Tested on Win10 mobile with Anniversary update.
=> Remove exit() call on hardware back button tap

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
no longer swollow the exceptions made in the NavigateAsync method.  We log and re-throw.
Fixes issue #1024.
=> [XF] NavigationService: no longer swallow exceptions

Source/Xamarin/Prism.Forms.Tests/Common/PageUtilitiesFixture.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/MasterDetailPageMock.cs, Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Fixes issue #1063 .
- Fixed to call Destroy of MasterPage
=> Fix Destroy for MasterDetailPage.

Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs, Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs, Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs, Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
Overrides the Xamarin Forms Current Property to provide the `PrismApplication`. This will make it easier when needing to reference the Container in situations where it might not otherwise be available such as in View Renderer's, Converters, and other View related code which would typically rely on the Xamarin Forms `DependencyService`.
=> make it easier to access the container

Source/Xamarin/Prism.Forms.Tests/Behaviors/EventToCommandBehaviorFixture.cs, Source/Xamarin/Prism.Forms/Behaviors/EventToCommandBehavior.cs
Fixes issue # #1085.
- Fix to terminate the search if null occurs while searching for nested properties
=> Fixed the behavior when null property was specified in EventArgsParameterPath of EventToCommandBehavior

Source/Prism/Mvvm/ErrorsContainer.cs
Fixes issue #: n/a
- Adds a method to clear all errors on ErrorsContainer. This is useful for resetting a form to default state. Without this change, the developer is forced to create a derived class to access the protected member containing the keys.
=> Added method to clear all errors on ErrorsContainer

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyNavigationPage.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/ViewModels/ContentPageMock1ViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/ContentPageMock1.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Opening this PR for comments and to  get Prism to work better with Xamarin.Forms
Fixes issues #765 , #1046 , #1054 
Addressed bugs opened on XF repo:
- https://bugzilla.xamarin.com/show_bug.cgi?id=44115
- https://bugzilla.xamarin.com/show_bug.cgi?id=45978
- https://bugzilla.xamarin.com/show_bug.cgi?id=56593
-  This PR changes the way the `PageNavigationService `is implemented to fit the Xamarin.Forms navigation more properly, there are some assumptions made in this class about the `NavigationProxy `that XF exposes on all Page types. 
If we have a `NavigationPage ` XF assumes the pages to be pushed are ContentPages, some users may use other type like MDP, this is not recomended, MDP should only be used as root, as to push a tabbed page it Works but we …
=> Navigation fixes

Source/Xamarin/Prism.Forms.Tests/Mvvm/ViewModelLocatorFixture.cs
Fixes issue #1068 .
Change the behavior only for a specific Page.
Other than that, I modified it to do normal behavior.
=> Fix to ShouldUseCustomDefaultViewTypeToViewModelTypeResolverWhenSet

Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs
Fixes issue #1070 
- Hardware BackButton event listener should be removed at compile time for UWP (Windows 10)
=> Back buttons on UWP will all raise the BackRequested event, fixes #1070

Source/Xamarin/Prism.Autofac.Forms.Tests/Mocks/PrismApplicationMock.cs, Source/Xamarin/Prism.Autofac.Forms/AutofacExtensions.cs, Source/Xamarin/Prism.Autofac.Forms/IPlatformInitializer.cs, Source/Xamarin/Prism.Autofac.Forms/Modularity/AutofacModuleInitializer.cs, Source/Xamarin/Prism.Autofac.Forms/Navigation/AutofacPageNavigationService.cs, Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs, Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Updates Autofac implementation to better work with the way that the Autofac API is designed to work.
- Removes the `IContainer` dependency for Prism Services in favor of the `IComponentContext` which is actually resolvable by the container.
- Changes PrismApplication to use the `ContainerBuilder` rather than `IContainer` and exposes this through the `Builder` property, while overriding and exposing the `Container` property as the final built container.
- Removes unnecessary factory registrations for Prism Services
- Updates View registration extensions to be extensions of the `ContainerBuilder` and not `IContainer`.
- Removes all deprecated uses of `builder.Update(Container)`
- Exposes the platform initializer as a protected property in `PrismApplicationBase` so that the Autofac …
=> Autofac updates

Source/Prism/Commands/PropertyObserver.cs, Source/Prism/Commands/PropertyObserverNode.cs
I found that the original implementation of this function has the following two points can be optimized (in `Source/Prism/Commands/PropertyObserverNode.cs` and `Source/Prism/Commands/PropertyObserver.cs`):
1. When registering a listener for each property in the property chain, two operations are REPEATED: **search expression root** and **get the instance of the property by reflection**.  The following recursive method shows this process (in `Source/Prism/Commands/PropertyObserverNode.cs`): 
```csharp
private static object GetPropertyValue(Expression expression)
{
object result;
if (expression is MemberExpression)
{
MemberExpression memberExpression = expression as MemberExpression;
string propertyName = memberExpression.Member.Name;
object propertyOwnerObject = …
```
=> Optimize the implementation of DelegateCommand.ObservesProperty

Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Ninject.Forms/Extensions/DependencyServiceBindingResolver.cs, Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
updates Xamarin.Forms to 2.4.0 SR1
updates/downgrades Ninject from 4.0 alpha to v3.3 stable. 
NOTE: change to Ninject version now requires targeting netstandard2.0
=> Package updates

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/project.json, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/SomeOtherViewModel.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/MyTabbedPageViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/packages.config, Source/Xamarin/Prism.Forms.Tests/Common/PageUtilitiesFixture.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationRecord.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/NavigationPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Views/TabbedPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
We are making a **breaking change** to the behavior of navigating to a TabbedPage.
`NavigateAsync("TabbedPage/ViewA/ViewB")` will select the tab ViewA in the TabbedPage if it exists, then continue navigating.  If ViewA does not exist as a tab, then you will continue to navigate as expected.
`NavigateAsync("TabbedPage/NavigationPage/ViewA/ViewB")` would search the TabbedPage for the first instance of a tab that was a NavigationPage, then navigate within the Navigation page the remaining ViewA and ViewB pages.  This provided the ability to deep link into a tab's nested navigation page, but there was no way to opt-out of this behavior.
Also, the INavigationAware methods did not get called to all tabs meaning that you would be responsible for forwarding any parameters to all your tabs. …
=> Tabbed page behavior change

Source/Windows10/Prism.Windows/Navigation/FrameNavigationService.cs
When following `App.xaml.cs` is used and the app is `suspended` when `resuming` then a KeyNotFoundException is raised:
~~~
sealed partial class App : PrismUnityApplication
{
public App()
{
this.InitializeComponent();
}
protected override UIElement CreateShell(Frame rootFrame)
{
//only a sample initialization: I use a different one
rootFrame.Content = new MainPage();
return rootFrame;
}
protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
{
return Task.FromResult<object>(null);
}
protected override void ConfigureContainer()
{
base.ConfigureContainer();
RegisterTypeIfMissing(typeof(IDataRepository), typeof(DataRepository), true);
}
}
~~~
The reason why I use such a construct and is because I use the `HamburgerMenu` from `UWPCommunityToolkit` and therefore I need a …
=> [Fix] RestoreNavigation: Possible KeyNotFoundException

Source/Xamarin/Prism.Forms/AppModel/IApplicationLifecycleAware.cs, Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Fixes issue #1198.
- Rename IApplicationLifecycle to IApplicationLifecycleAware
=> Rename IApplicationLifecycle to IApplicationLifecycleAware

Source/Xamarin/Prism.Forms.Tests/Navigation/INavigationServiceExtensionsFixture.cs, Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs
Added a new extension for the navigation service that will allow devs to pop all pages off a NavigationPage's nav stack
Fixes issue #1200
=> added PopToRootAsync method

Source/Xamarin/Prism.Forms.Tests/Mocks/Views/TabbedPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/ViewModels/Tab1MockViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/ViewModels/Tab2MockViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/ViewModels/Tab3MockViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/Views/Tab1Mock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/Views/Tab2Mock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/Views/Tab3Mock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Automatically adding VML.AutowireViewModel to tabs.
Also added the NavigationPageActiveAwareBehavior by default.
Removed the requirement of providing the `selectedTab=NaviationPage|TabToSelect` syntax to select a tab.  Now, just provide the `selectedTab=TabToSelect` and if it is in a NavigationPage, it will be selected automatically.
=> added behavior and set VML to children

docs/Xamarin-Forms/6-EventToCommandBehavior.md
Fixes issue # .
- Fix typo in docs: EventToCommandBehavior tried to use StackLayout instead of ListView
=> Fix Typo in using StackLayout instead of ListView

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyTabbedPage.xaml, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/Views/TabbedPageEmptyMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
You can now dynamically create tabs when navigating to a TabbedPage by using the `KnownNavigationParameters.CreateTab` constant or by using the "createTab" parameter name.
`_navigationService.NavigateAsync("MyTabbedPage?createTab=ViewA&createTab=ViewB");`
This will create a TabbedPage and then create two tabs, ViewA and ViewB.
To create a tab that wraps a page in a NavigationPage, simply denote this as a nested hierarchy using the `|` character.
`_navigationService.NavigateAsync("MyTabbedPage?createTab=NavigationPage|ViewA");`
=> Dynamic tab creation for TabbedPage

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
This feature allows you to remove pages form the navigation stack of a NavigationPage while at the same time navigating to a new page.  For each page you wish to remove, prefix your navigation path with `../`.
**Example**
Our app requires a user to login in order to edit "User" profile information.  This will require the user to be prompted to login and then once successful continue to edit the profile.  This leaves us with the following navigation stack:
"NavigationPage/UserList/UserDetails/LoginPage/EditUser"
If we were to hit the back button from the `EditUser` page, we would be returned to the `LoginPage`.  This is not the desired experience.  Instead, we want to go back to the `UserDetails` which was just updated.  To achieve this we provide the following navigation URI from the …
=> Remove pages from navigation stack

README.md
-  Fixing link to renamed download-and-setup-prism file.
=> Fixing link to renamed download-and-setup-prism file

Source/Prism.Tests/Mvvm/BindableBaseFixture.cs
- fix argument order of Assert.Equal (expected, actual)
=> fix argument order of Assert.Equal

Source/Prism.Tests/Commands/DelegateCommandFixture.cs
- Fix argument order of Assert.Equal used in DelegateCommandFixture
=> Fix argument order of Assert.Equal used in DelegateCommandFixture

Source/Prism.Tests/Commands/DelegateCommandFixture.cs
-  Fix xUnit2004 warning. use Assert.True(b) instead of Assert.Equal(true, b).
=> Fix xUnit2004 warning

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs, Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs, Source/Xamarin/Prism.Forms/Navigation/KnownInternalParameters.cs, Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs, Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs, Source/Xamarin/Prism.Forms/Navigation/NavigationParametersExtensions.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Added a collection to the NavigationParameetrs class that can be used to track internal parameter infromation. This fixes #1225
=> added internal parameters

Source/Wpf/Prism.Autofac.Wpf/AutofacExtensions.cs, Source/Wpf/Prism.DryIoc.Wpf/DryIocExtensions.cs, Source/Wpf/Prism.Ninject.Wpf/NinjectExtensions.cs, Source/Wpf/Prism.Unity.Wpf/UnityExtensions.cs
Added new `RegisterTypeForNavigation<View, ViewModel>(key)` method to make overriding the ViewModelLocator naming convention easier.
=> added RegisterTypeForNavigation for VM extensions

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyTabbedPage.xaml, Source/Xamarin/Prism.Forms.Tests/Navigation/INavigationServiceExtensionsFixture.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/ViewModels/NavigationPathPageMockViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/Mocks/Views/NaviationPagePathPageMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationRegistryFixture.cs, Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationRegistry.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Fixes issue #1109 
You can now get the absolute navigation path of a page by calling `INavigationService.GetNavigationUriPath`.
There may be some edge cases that I may have missed but so far it works with the most complex navigation stacks I have tried.  These are just a few of the paths I have tested.
```
/NavigationPage/ViewA/MyTabbedPage/ViewC
/NavigationPage/ViewA/MyTabbedPage/ViewA/ViewB/ViewC
/NavigationPage/ViewA/ViewB/NavigationPage?useModalNavigation=true/ViewB/ViewC
/NavigationPage/ViewA/ViewB/ViewC?useModalNavigation=true
/MyMasterDetail/NavigationPage/MyTabbedPage/ViewA/ViewC?useModalNavigation=true
/ViewA/ViewB/MyMasterDetail/NavigationPage/ViewA/ViewC
/ViewA/ViewB/MyMasterDetail/ViewA/ViewC
/ViewA/ViewB/MyMasterDetail/NavigationPage/ViewA/ViewB?useModalNavigation=true/ViewA/V …
```
=> added support for GetNavigationUriPath

README.md
This PR just fixes links of AppVeyor build status badges. Now if you click a badge image you will redirect to a build page.
=> Fix links to AppVeyor builds

Source/Wpf/Prism.Wpf/Interactivity/InteractionRequest/Notification.cs
Notification now implements INotifyPropertyChanged, but doesn't actually call it. This is done to fix a known issues with the WPF binding system creating a memory leak when binding to an object that isn't a DO or implements INPC.
- #1297
=> Notification now implements INotifyPropertyChanged

Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Modules/ModuleMock.cs, Source/Xamarin/Prism.Forms/Modularity/IModule.cs, Source/Xamarin/Prism.Forms/Modularity/ModuleInitializer.cs
- Removes Initialize method
- Adds IContainerProvider to OnInitialized
- #1338 
- Prevents new modules from implementing the deprecated Initialize method as there is no warning that it is obsolete
- Aligns Prism.Forms `IModule` with Prism.Wpf `IModule` #1339 
Removed:
- `IModule.Initialize()`
Changed:
- `IModule.OnInitialized()` => `IModule.OnInitialized(IContainerProvider)`
=> #1338 adds IContainerProvider to OnInitialized, removes Initialize

Source/Prism.Tests/Prism.Tests.csproj, Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/ContainerProviderFixture.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Converters/MockValueConverter.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Events/TestActionEvent.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationMock.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlViewMockViewModel.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMock.xaml, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMock.xaml.cs, Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Forms/Ioc/ContainerProvider.cs, Source/Xamarin/Prism.Forms/PrismApplicationBase.cs, Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj, Source/xunit.runner.json
Adds ContainerProvider to resolve types in XAML
- Fixes #1347 
- Should fix randomly failing tests...
Added:
- ContainerProvider<T> to allow resolving types in XAML
```xml
<ContentPage xmlns:ioc="clr-namespace:Prism.Ioc;assembly=Prism.Forms"
xmlns:converters="using:MyApp.Converters">
<ContentPage.Resources>
<ResourceDictionary>
<ioc:ContainerProvider x:TypeArguments="converters:MyAwesomeConverter" 
x:Key="myConverter" />
</ResourceDictionary>
</ContentPage.Resources>
<Label Text="{Binding Foo,Converter={StaticResource myConverter}}" />
</ContentPage
```
none
=> Container provider

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleAModule.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/MyCarouselPageViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyCarouselPage.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyCarouselPage.xaml.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Added support for the INavigationAware methods for the CarouselPage
- #1354 
The INavigationAware methods now properly fire for both the CarouselPage and the children of the CarouselPage.
Some INavigationAware methods are now fired on all Children:
- OnNavigatingTo will be invoked on the CarouselPage and ALL CHILDREN.
- OnNavigatedTo will be invoked on the CarouselPage and only the SELECTED PAGE.
- OnNavigatedFrom will be invoked on the CarouselPage and only the SELECTED PAGE.
=> added support for INavAware methods on CarouselPage

Source/Prism.Tests/Prism.Tests.csproj, Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PrismApplicationFixture.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Navigation/CustomNavigationServiceMock.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationCustomNavMock.cs, Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Adding tests for Custom Navigation Service. Due to the very unique way that we are injecting the NavigationService in DryIoc we actually have `INavigationService` registered twice, once as a named service and once as an unnamed service. The Unnamed version is what gets used when we inject it into a ViewModel.
- #1381 Tests
None
None
=> DryIoc tests

Source/Prism/Prism.csproj, Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj, Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Due to the breaking changes that have been made for cross platform compatibility with INavigationService, and other upcoming changes Prism Core and all Prism Forms projects are bumping to 7.1. Prism WPF/Windows are staying at 7.0 since they have yet to release a stable package.
=> bump to 7.1

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/project.json, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/app.config, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/packages.config, Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj, Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj, Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj, Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
We have improved the relative back navigation feature to not require a page to push after the relative back instructions.
Previously, when using the relative back feature ("../" ) you would be required to provide a page that would be pushed onto the navigation stack.  That is no longer required.  You may now chain together any number of relative go-back instructions to "go back".
For example:
Given your navigation stack looked like this: `NavigationPage/UserList/UserDetails/LoginPage/EditUser`
You can now indicate how many pages to remove, or "go back" by chaining the relative go-back instruction "../".
`NavigationService.NavigateAsync("../../../");`
This would result in going back three pages leaving you with the following navigation stack: …
=> Implemented relative back behavior ("../../")

Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Pass parameters to `GoBackAsync` within `RemoveAndGoBack`.
[Issue 1409](https://github.com/PrismLibrary/Prism/pull/1409)
None.
None.
=> Fixes issue #1456

Source/Xamarin/Prism.Autofac.Forms/AutofacContainerExtension.cs, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PrismApplicationFixture.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/ViewModels/CustomNamedNavServiceViewModel.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/CustomNamedNavService.cs, Source/Xamarin/Prism.Unity.Forms/UnityContainerExtension.cs
Fixes #1464 
Unity and Autofac now allow INavigationService to have any name inside of a ViewModel.
None
ViewModels may now name INavigationService anything when resolving inside of a ViewModel handled by the ViewModelLocator.
=> Allow type based resolution for INavigationService in ViewModels

Source/Prism.Tests/Events/DelegateReferenceFixture.cs, Source/Prism.Tests/Events/PubSubEventFixture.cs, Source/Prism/Commands/DelegateCommand.cs, Source/Prism/Commands/DelegateCommandBase.cs, Source/Prism/Commands/DelegateCommand{T}.cs
Fixes tests that were randomly failing because the Garbage Collection wasn't collecting a nulled reference. Updated tests now add a slight delay between setting a reference to null and performing the Garbage Collection allowing the runtime to properly identify the reference as needing collection.
- Fixes Tests Only
None
None
=> Test updates

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.xaml.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/PartialViewBViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/PartialViewB.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/Views/PartialViewB.xaml.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewB.xaml, Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj, Source/Xamarin/Prism.Autofac.Forms/AutofacContainerExtension.cs, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/FixtureBase.cs, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PartialViewFixture.cs, Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PrismApplicationFixture.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationMock.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/ViewModels/PartialViewModel.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/PartialView.xaml, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/PartialView.xaml.cs, Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMock.xaml, Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, Source/Xamarin/Prism.DryIoc.Forms/DryIocContainerExtension.cs, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Forms/Common/PageUtilities.cs, Source/Xamarin/Prism.Forms/Mvvm/ViewModelLocator.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Forms/Properties/AssemblyInfo.cs, Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj, Source/Xamarin/Prism.Unity.Forms/UnityContainerExtension.cs, Source/global.json
Adds an ability to support Partial Views that have their own ViewModel which can be reused across multiple Pages in a single application. This sets the AutowireViewModel property behind the scenes and updates the ResolveViewModelForView in each of the Container projects to look for an associated Page if the View is not a Page.
```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
xmlns:local="using:AwesomeProject.Views"
x:Name="page"
x:Class="AwesomeProject.Views.ViewA">
<local:MyCustomView prism:ViewModelLocator.AutowirePartialView="{x:Reference page}" />
</ContentPage>
```
```cs
public class MyCustomViewModel : BindableBase
{ …
```
=> Support Partial Views in Xamarin Forms

README.md, Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationContainerMock.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/INavigationServiceExtensionsFixture.cs, Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationRegistryFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationRegistry.cs
Adding API to clear the Navigation Registry for Xamarin.Forms. This helps when unit testing across multiple fixtures.
n/a
Added:
PageNavigationRegistry
- static void ClearRegistrationCache();
n/a
=> Clear registry

Source/Xamarin/Prism.Forms/Properties/AssemblyInfo.cs
Adding linker Preserve Attribute to Prism.Forms
N/A
N/A
Linking Xamarin.iOS projects will now leave Prism.Forms alone reducing issues in which the Linker removes references to Prism implementations.
=> add Linker Preserve Attribute

README.md
Several myget urls had a trailing slash causing the link to force a login﻿. This has been fixed.
Old https://myget.org/feed/prism/package/nuget/Prism.Core/
New https://myget.org/feed/prism/package/nuget/Prism.Core
=> [Documentation] Fixed myget urls

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
if the current detail is a navPage, we need to call OnNavigatedFrom on the navage.CurrentPage
- #1589 
none
=> fixed #1589

Source/Wpf/Prism.Wpf/PrismApplicationBase.cs
This always loads the modules even when no shell was created.
It also makes sure to not crash afterwards when MainWindow is null.
https://github.com/PrismLibrary/Prism/issues/1601
None
InitializeModules() is called for WPF application even when there's no shell created in CreateShell()
=> Load modules without a shell in WPF applications (#1601)

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.xaml.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewBViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyTabbedPage.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewB.xaml, Source/Xamarin/Prism.Forms/Navigation/TabbedPages/INavigationServiceExtensions.cs
Added a new extension method to `INavigationService` that allows a developer to select a tab from within the same TabbedPage instance.
Added:
- void INavigationService.SelectTab(name, parameters);
To use the new extension method, add the `Prism.Navigation.TabbedPages` namespace to your ViewModel.
`IConfirmNavigation` and `INavigationAware` interfaces are respected.
=> added SelectTab extension method for tabbedpages

Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewBViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs, Source/Xamarin/Prism.Forms/Navigation/TabbedPages/INavigationServiceExtensions.cs
Normalizes the API to match other Navigation methods with INavigationResult. Adds check of the NavigationPage Root Page when determining which tab to switch to. 
Tabs containing a NavigationPage will switch whether you know the root or current page within the navigation stack. However no actual navigation will occur within the NavigationPage.
Changed:
- Task INavigationService.SelectTab> => Task<INavigationResult> INavigationService.SelectTabAsync
- Tab Selection will now take into account both the Current and Root Page of tabs containing a Navigation Page.
=> Tabbed Switching Refactoring

Source/Windows10/Prism.DryIoc.Windows/DryIocContainerExtension.cs, Source/Windows10/Prism.Unity.Windows/UnityContainerExtension.cs
Changed the behaviour of {Unity|DryIoc}ContainerExtension.ResolveViewModelForView() to be able to resolve VM for a view that is a page, but doesn't have its frame associated.
#1628 
None
None
=> Properly resolve viewmodels for particular views in UWP

Source/Prism/Commands/DelegateCommand{T}.cs
Just fixed a small typo.
Before:
`When both executeMethod and canExecuteMethod ar null.`
After:
`When both executeMethod and canExecuteMethod are null.`
=> Fix typo in documentation of DelegateCommand<T>

Source/Windows10/Prism.Windows/Navigation/INavigationServiceExtensions.cs, Source/Xamarin/Prism.Forms.Tests/Services/PageDialogServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs, Source/Xamarin/Prism.Forms/Services/PageDialogService/ActionSheetButton.cs
The included changes provide a little syntactic sugar to the existing APIs 
n/a
ActionSheetButton - eliminate the requirement to pass in either an Action or Command for Cancel/Destroy buttons where the intent may simply be to dismiss the dialog.
Added:
- static IActionSheetButton CreateCancelButton(string)
- static IActionSheetButton CreateDestroyButton(string)
INavigationService - now that we're making use of Tuples across the board with IContainerProvider, adding extension methods to allow simply passing in Tuples rather than having to explicitly create new NavigationParameters. Added for both Prism.Windows and Prism.Forms
- Task<INavigationResult> NavigateAsync(string, params (string, object)[])
- Task<INavigationResult> NavigateAsync(Uri, params (string, …
=> API Enhancements

Source/Prism/Commands/PropertyObserver.cs, Source/Prism/Commands/PropertyObserverNode.cs
https://github.com/PrismLibrary/Prism/issues/1676
- [x ] Has tests (if omitted, state reason in description)
- [x ] Changes adhere to coding standard
=> Changed property observer to use property info instead of property name

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/Resources/Resource.designer.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj, Source/Xamarin/Prism.Forms/Navigation/Xaml/GoBackExtension.cs, Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigateToExtension.cs, Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs
- XAML navigation animated parameter, issue #1683 
- Xamarin.Forms in sample app updated to 3.5., I wasn't able even compile the project because Prism.Forms has dependency on 3.5 and sample app had to 3.3
- I didn't find any tests for this xaml extension
Added:
- bool NavigationExtensionBase.Animated
=> xamarin forms xaml navigation animated

Source/Prism/Ioc/IContainerRegistry.cs, Source/Prism/Ioc/IContainerRegistryExtensions.cs, Source/Windows10/Prism.DryIoc.Windows/DryIocContainerExtension.cs, Source/Windows10/Prism.Unity.Windows/UnityContainerExtension.cs, Source/Wpf/Prism.DryIoc.Wpf/Ioc/DryIocContainerExtension.cs, Source/Wpf/Prism.Ninject.Wpf/Ioc/NinjectContainerExtension.cs, Source/Wpf/Prism.Unity.Wpf/Ioc/UnityContainerExtension.cs, Source/Wpf/Prism.Wpf.Tests/Mocks/MockContainerAdapter.cs, Source/Xamarin/Prism.DryIoc.Forms/DryIocContainerExtension.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationContainerMock.cs, Source/Xamarin/Prism.Unity.Forms/UnityContainerExtension.cs
Updates IContainerRegistry to allow registration chaining
fixes #1677 
n/a
Changed:
- void IContainerRegistry.Register => IContainerRegistry IContainerRegistry.Register
- void IContainerRegistry.RegisterSingleton => IContainerRegistry IContainerRegistry.RegisterSingleton
- void IContainerRegistry.RegisterInstance => IContainerRegistry IContainerRegistry.RegisterInstance
n/a
=> Fluent API for IContainerRegistry fixes #1677

Sandbox/Wpf/HelloWorld/HelloWorld/App.xaml.cs, Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/ConfirmationDialog.xaml, Source/Wpf/Prism.Wpf/Ioc/IContainerRegistryExtensions.cs, Source/Wpf/Prism.Wpf/Properties/AssemblyInfo.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/DefaultDialogs/DialogWindow.xaml, Source/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogWindow.cs
You can now control the properties of the DialogWindow by using a style via an attaxched property on the Dialog UserControl
```
<prism:DialogService.DialogWindowStyle>
<Style TargetType="Window">
<Setter Property="ResizeMode" Value="NoResize"/>
<Setter Property="ShowInTaskbar" Value="False"/>
<Setter Property="SizeToContent" Value="WidthAndHeight"/>
</Style>
</prism:DialogService.DialogWindowStyle>
```
_NOTE_ I'm not real happy with the location of the attached property and it may be moved to a different class.
Added:
- DialogService.DialogWindowStyle attached property
- Added IDialogWindow.Style property
=> added support to control DialogWindow propertes from style

Source/Xamarin/Prism.Forms/AppModel/RuntimePlatform.cs, Source/Xamarin/Prism.Forms/Ioc/AutoRegisterForNavigationAttribute.cs, Source/Xamarin/Prism.Forms/Ioc/RegisterByConventionAttribute.cs, Source/Xamarin/Prism.Forms/Ioc/RegisterForNavigationAttribute.cs, Source/Xamarin/Prism.Forms/Ioc/TypeAutoLoadExtensions.cs, Source/Xamarin/Prism.Forms/Modularity/ModuleInitializer.cs, Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Adds support for registration Views either through Attributes or automatically for all pages in the Assembly. This will register Views in the same assembly as the Prism Application or Module
Added:
- AutoRegisterForNavigationAttribute 
```cs
[AutoRegisterForNavigation]
public partial class App : PrismApplication
{
}
[AutoRegisterForNavigation(Automatic = true)]
public class ModuleA : IModule
{
}
```
- RegisterForNavigationAttribute 
The RegisterForNavigationAttribute can be added either at an assembly level or at the class level to any Page. Note that if added to a Page the Type of the Page it's added to will override anything you manually add. The ViewType is required when adding the attribute at the …
=> Automatic View Registration

Source/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs
If you create and show a new Window in Prism and then try to navigate within regions, it will fail because there is no RegionManager associated with the new Window object.
The IDialogService has been modified to automatcally assign the application's RegionManager to eacvh dialog window instance so that region navigation will work out of the box
- #1805 
None
Region navigation will now function properly when navigating within the IDialogService
=> Attached RegionManager to dialog by default

Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
Removes FastExpressionCompiler from DryIoc Forms due to incompatibility with iOS due to it attempting to JIT.
- fixes #1806 
none
prevents new API from DryIoc 4 from causing crashes on iOS
=> Removes FastExpressionCompiler from DryIoc Forms

Source/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs
﻿## Do not override owner in DialogService
- [#1666](https://github.com/PrismLibrary/Prism/issues/1666#issuecomment-496558216)
None
Check DialogWindow's Owner whether is null during configuration.
=> Do not override owner in DialogService

Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/DialogViewModelBase.cs, Sandbox/Wpf/HelloWorld/HelloWorld/ViewModels/MainWindowViewModel.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/ButtonResult.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/DialogParameters.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/DialogResult.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogAware.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogResult.cs, Source/build/azure-pipelines.yml
Removed the use of a `bool?` as the `IDialogResult.Result` property. Instead, added a new enum called `ButtonResult`
Added:
```
public enum ButtonResult
{
Abort = 3,
Cancel = 2,
Ignore = 5,
No = 7,
None = 0,
OK = 1,
Retry = 4,        
Yes = 6
}
```
Changed:
- `bool? IDialogResult.Result` => `ButtonResult IDialogResult.Result`
The `IDialogResult.Result` property no longer returns a `bool?`, instead is now returns a `ButtonResult` enum value.
=> Using Enum for IDialogResult.Result

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MyMasterDetailViewModel.cs, Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml, Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs, Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewA.xaml, Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs, Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameterExtensions.cs, Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs
Fully supports Bindings for Xaml Navigation. You can now use bindings without issue for any of the Properties on the Navigation Extensions or the XAML Navigation Parameters.
- fixes #1754
none
none
=> Fully support bindings for Xaml Navigation 

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml, Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs, Source/Xamarin/Prism.Forms/Services/Dialogs/Xaml/DialogLayout.cs, Source/build/steps/build.yml
Small bug fixes and enhancements for DialogService
- Fixes crash on Android with Screen Reader caused by reparenting ordering
Added:
- UseMask attached property to allow the opting out of having a mask layer
- CloseOnBackgroundTapped attached property to specify it as 
- Sets MasterDetailPage.IsPresented to false. This helps when invoked from the XAML Extension from the MasterDetailPage.Master
=> Dialog Updates

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs, Source/Xamarin/Prism.Forms/Mvvm/ViewModelLocator.cs
Currently, when a partial-view removes itself from the Page by calling `SetAutowirePartialView(view, null)`, all the other partial views are also removed from the Page's inner partial view collection.
This PR makes only the partial view calling `SetAutowirePartialView(view, null)` be removed.
This gives the possibility to add/remove partial views dynamically.
#1726
None
See description
=> Partial views changes

Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs, Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
This makes `NavigationService.Push` return a `NavigationResult` with a `NavigationException` when the navigation is cancelled via `IConfirmNavigation`/`IConfirmNavigationAsync`'s `CanNavigate` method.
- Fixes #1912 
None
If a ViewModel tries to navigate and `CanNavigate` returns false, it will now return a `NavigationResult` with a `NavigationException` and `Success = false`. This makes `Push` consistent with the same behavior in `Back` and `BackToRoot`.
=> Fills NavigationResult Exception for Navigations where CanNavigate is false

Source/Xamarin/Prism.Forms.Tests/Services/DialogServiceTests.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/Dialogs/DialogMock.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/Dialogs/DialogMockViewModel.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/Ioc/DialogContainerExtension.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/Ioc/IRegistration.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/Ioc/TransientRegistration.cs, Source/Xamarin/Prism.Forms.Tests/Services/Mocks/MockApplication.cs, Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs
Fixes a few bugs and adding overdue tests for DialogService. Note that layout specific tests could not be added for Relative Height/Width as we would have to generate some renderers for the test harness to get it to actually do a proper layout.
- Fixes #1894 Relative Height bug from some copy paste
- Fixes #1883 Null callback action would generate NullReferenceException
- Fixes issue with UseMask property being evaluated on the wrong element
none
none
=> Dialog service fixes

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs, Source/Xamarin/Prism.Forms/Ioc/TypeAutoLoadExtensions.cs
Sometimes, we need to define some generic abstract classes. This could be the case for ContentPage like:
MyAbstractContentPage<TOtherClass> : ContentPage where TOtherClass : IWhateverInterface
and then:
MyContentPage : MyAbstractContentPage<MyOtherClass>
The problem is using AutoRegisterForNavigation attribute try to register MyAbstractContentPage<TOtherClass> and fails with container exception about registering open generic.
So I just added some filters on registration to ignore open generic classes.
- AutoRegisterForNavigation attribute throw a container registration exception when using generic page class in project
Changed:
- var viewTypes = assembly.ExportedTypes.Where(t => t.IsSubclassOf(typeof(Page))); 
=> 
var viewTypes = assembly.ExportedTypes.Where(t => …
=> Open generic pages and double tabs navigation

Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs
While this shouldn't theoretically be an issue, this ensures we set the Binding Context of the Page Content to the Binding Context of the Page before we update the Page's content to display a Dialog.
- fixes #1948 
none
shouldn't be any changes
=> Maintain Binding Context for Dialogs

Source/Prism.Tests/Common/Mocks/MockEnum.cs, Source/Prism.Tests/Common/Mocks/MockParameters.cs, Source/Prism.Tests/Common/ParametersFixture.cs, Source/Prism.Tests/Mvvm/AutoInitializeViewModelFixture.cs, Source/Prism/Common/ParametersExtensions.cs, Source/Xamarin/Prism.Forms.Tests/Mvvm/AutoInitializeFixture.cs, Source/Xamarin/Prism.Forms.Tests/Mvvm/Mocks/ViewModels/AutoInitializedViewModelMock.cs, Source/Xamarin/Prism.Forms.Tests/Mvvm/Mocks/ViewModels/MockHttpStatus.cs
This is a rebased and fixed version of PR #1916. This adds tests both for ParametersBase and IAutoInitialize specifically. Be sure to note some of the behavior changes.
- no issue was created
none
Updates GetValue / TryGetValue from the ParametersBase. All Get Value methods now use a single internal TryGet method so that the conversion from the KeyValuePair's Value (which may be a string if it was from the QueryString) to whatever the requested type is will use the same exact logic. We now will be intentional in throwing an InvalidArgumentException when calling GetValue in the event that we could not convert the value to the requested type. 
This also fixes a very incorrect assumption that at the event you got to the end of our type conversion logic that the value must be convertible. …
=> Adding Enum support from QueryStrings

Source/Wpf/Prism.Wpf.Tests/Regions/RegionNavigationJournalFixture.cs, Source/Wpf/Prism.Wpf/Regions/RegionNavigationJournal.cs, Source/Wpf/Prism.Wpf/Regions/RegionNavigationService.cs
Changed RegionNavigationJournal logic to properly handle the CurrentEntry for views no being added to the nav journal by using the IJournalAware
#1850 
The Journal.CurrentEntry does not get set to a view that is not persisted in the Journal
=> Fixed CurrentEntry for views not in Journal

Sandbox/Wpf/HelloWorld/HelloWorld/App.xaml.cs, Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/AnotherDialogWindow.xaml, Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/AnotherDialogWindow.xaml.cs, Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/NotificationDialog.xaml, Sandbox/Wpf/HelloWorld/HelloWorld/HelloWorld.csproj, Sandbox/Wpf/HelloWorld/HelloWorld/ViewModels/MainWindowViewModel.cs, Sandbox/Wpf/HelloWorld/HelloWorld/Views/MainWindow.xaml, Source/Wpf/Prism.Wpf/Ioc/IContainerRegistryExtensions.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs, Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogService.cs
Added support for multiple dialog window hosts. Now when registering a dialog window to act as a dialog host, you can now specify a named dialog window. Using this name, you can then show a specific dialog window when calling `IDialogService.Show` or `IDialogService.ShowDialog`
First register your dialog window with a name:
```
containerRegistry.RegisterDialogWindow<AnotherDialogWindow>("myAwesomeDialogWindow");
```
Then to show you dialog window, provide the name in the `Show()` or `ShowDialog()` methods
```
_dialogService.Show("NotificationDialog", new DialogParameters($"message={message}"), r =>
{
//handle result and parameters in callback
}, "myAwesomeDialogWindow");
```
- #1903 
Added:
- static void …
=> added support for multiple dialog windows

Source/Prism/Modularity/IModuleManager.cs, Source/Prism/Modularity/ModuleDownloadProgressChangedEventArgs.cs, Source/Prism/Prism.csproj, Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.net45.cs, Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.netcore.cs, Source/Wpf/Prism.Wpf/Mvvm/ViewModelLocator.cs, Source/Wpf/Prism.Wpf/Prism.Wpf.csproj, Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs, Source/Xamarin/Prism.Forms/Modularity/ModuleManager.cs, Source/Xamarin/Prism.Forms/Prism.Forms.csproj, Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
Removes compiler directives that were simply no longer needed.
Updates Prism.Wpf to compile by convention
- Files named `{filename}.net45.cs` will compile for the net45 target but not the netcore target
- Files named `{filename}.netcore.cs` will compile for the netcore target but not the net45 target
=> removing unnecessary compiler directives

Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BadInitializationModule.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BadModule.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BasicCatalog.xaml, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BasicCatalog.xaml.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BasicDependencyCatalog.xaml, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/BasicDependencyCatalog.xaml.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/DependentModuleA.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/DependentModuleB.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/MasterModule.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/ModuleA.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/ModuleB.cs, Source/Xamarin/Prism.Forms.Tests/Mocks/Modules/ModuleC.cs, Source/Xamarin/Prism.Forms.Tests/Modularity/ModuleFixture.cs, Source/Xamarin/Prism.Forms/Modularity/ModuleInfo.cs
Ensures that ModuleName is not null/empty
- fixes #1989 
n/a
Prevents ModuleName from being null/empty
=> Ensure ModuleName is provided

Source/Xamarin/Prism.Forms/Behaviors/IPageBehaviorFactory.cs, Source/Xamarin/Prism.Forms/Behaviors/PageBehaviorFactory.cs
Removes Page Type specific methods from the IPageBehaviorFactory interface as none of these are called externally. Updates the PageBehaviorFactory implementation:
- [BREAKING] All existing methods are now protected instead of public
- Implementation for ApplyPageBehaviors is inside of explicit implementation of the IPageBehaviorFactory. This guards against developers accidentally forgetting and thus eliminates the need to call base.ApplyPageBehaviors.
closes #1999
n/a
See description
=> Only expose ApplyPageBehaviors

Source/Directory.Build.props, Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
Enables strong name assembly signing for Prism.DryIoc
- Fixes #2014
n/a
n/a
=> Enable Strong Name for Prism.DryIoc

Source/Wpf/Prism.Wpf/Regions/RegionManager.cs
Adds a generic method for the RegionManager.RegisterViewWithRegion method
- #2027 
Added:
`RegionManager.RegisterViewWithRegion<ViewA>("ContentRegion");`
=> added RegisterViewWithRegion generic method

Source/Wpf/Prism.Wpf.Tests/Regions/RegionAdapterMappingsFixture.cs, Source/Wpf/Prism.Wpf/Regions/RegionAdapterMappings.cs
Added generic method to the RegionAdapterMappings to simplify registering new adapters.
- #2026 
Added:
`regionAdapterMappings.RegisterMapping<StackPanel, StackPanelRegionAdapter>();`
=> added RegiserMappings generic method

Sandbox/Wpf/HelloWorld/HelloWorld/HelloWorld.csproj, Source/Directory.Build.props, Source/Prism.Tests/Prism.Tests.csproj, Source/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj, Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj, Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Prism.IocContainer.Wpf.Tests.Support.csproj, Source/Wpf/Prism.Ninject.Wpf.Tests/Prism.Ninject.Wpf.Tests.csproj, Source/Wpf/Prism.Ninject.Wpf/Prism.Ninject.Wpf.csproj, Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj, Source/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj, Source/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj, Source/Wpf/Prism.Wpf/Prism.Wpf.csproj, Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj, Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj, Source/global.json
Updates Prism to require NetCoreApp3.1 instead of NetCoreApp3.0
- n/a
- n/a
n/a
=> Update to NetCoreApp3.1

Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs
The current solution does not support dialogs on modal pages, it opens dialog on last non-modal page, these changes search for the last modal page if it exists
- If current appeared page is a modal page, DialogService will open dialog on last non-modal page
None
Dialogs could be opened on modal pages
=> Update DialogService to support modal pages

build/steps/prepare-build.yml, src/Prism.Core/Events/PubSubEvent.cs, tests/Prism.Core.Tests/Events/PubSubEventFixture.cs
Add an overload to the event aggregation to provide the action and filter
- #2046 
Added:
`SubscriptionToken Subscribe(Action<TPayload> action, Predicate<TPayload> filter)`
=> Added overload for IEventAggregator to provide filter

src/Wpf/Prism.Wpf/Services/Dialogs/ButtonResult.cs, src/Wpf/Prism.Wpf/Services/Dialogs/Dialog.cs, src/Wpf/Prism.Wpf/Services/Dialogs/DialogResult.cs, src/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs, src/Wpf/Prism.Wpf/Services/Dialogs/DialogWindow.xaml.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogAware.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogResult.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogService.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogWindow.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogWindowExtensions.cs
Added documentation - issue #1978
Project: Prism.Wpf
Namespace Prism.Services.Dialogs
None
None
None
=> Added XML Docs to Prism.Wpf - Prism.Services.Dialogs

src/Forms/Prism.Forms/Navigation/INavigationServiceExtensions.cs, src/Forms/Prism.Forms/Navigation/PageNavigationService.cs, src/Forms/Prism.Forms/Navigation/TabbedPages/INavigationServiceExtensions.cs, src/Forms/Prism.Unity.Forms/PrismApplication.cs, src/Prism.Core/Common/ParametersBase.cs, src/Prism.Core/Modularity/IModuleInfo.cs, src/Prism.Core/Modularity/IModuleInfoGroup.cs, src/Wpf/Prism.DryIoc.Wpf/Legacy/DryIocExtensions.cs
Fixed some CS1572, 1573, 1574 and 1591 warnings
- Adding some missing XML Docs - issue #1978
None
None
- [] Changes adhere to coding standard
=> Fixed some CS1572, 1573, 1574 and 1591 warnings

build/jobs/uno-uitest.yml, e2e/Uno/HelloUnoWorld.Shared/ViewModels/ShellViewModel.cs, e2e/Uno/HelloUnoWorld.UITests/Constants.cs, e2e/Uno/HelloUnoWorld.UITests/Dialog_Tests.cs
- Aligns the UI Tests for using the default dialog after the removal of the custom dialog.
- Use the set-runtime step to force the mono runtime version on macOS builds.
None.
None.
=> [Uno] Adjust UI Tests, force mono version for macOS builds

tests/Wpf/Prism.Wpf.Tests/PrismBootstapperBaseFixture.cs
Added unit tests for the new PrismBootstrapperBase class.
=> Added unit tests for new PrismBootstrapperBase

src/Prism.Core/Extensions/TaskExtensions.cs, src/Prism.Core/Extensions/TaskExtensions{T}.cs, tests/Prism.Core.Tests/Extensions/TaskExtensionsFixture.cs
We added extension methods to the Task object to allow developers to execute and await Task based methods in void method declarations.
- #2082
Added:
Added variations of the follow APIs:
- `public async static void Await(this Task task, Action completedCallback, Action<Exception> errorCallback, bool configureAwait)`
- `public async static void Await<T>(this Task<T> task, Action<T> completedCallback, Action<Exception> errorCallback, bool configureAwait)`
=> added Task extensions for async/void tasks

tests/Wpf/Prism.Wpf.Tests/PrismBootstapperBaseFixture.cs
Added another test for the PrismBootstrapperBase class to verify that all required types have been registered.
=> Added PrismBootstrapper tests

src/Forms/Prism.Forms/Navigation/INavigationParameters.cs, src/Forms/Prism.Forms/Navigation/INavigationParametersInternal.cs, src/Wpf/Prism.Wpf/Bootstrapper.cs, src/Wpf/Prism.Wpf/Modularity/IModuleCatalogExtensions.cs, src/Wpf/Prism.Wpf/Regions/IRegionNavigationJournal.cs
Resolved some CS1573,1591 #1978 
- Resolved some CS1573,1591 #1978 
None
None
=> Resolved some CS1573,1591

build/jobs/uno-uitest.yml, build/scripts/android-uitest-run.sh, build/scripts/ios-uitest-run.sh, build/scripts/wasm-uitest-run.sh
This change disables build failures for the Android e2e tests on Uno Platform, and ensures that iOS and Wasm fail at the publishing step (and not the execution step).
- https://github.com/PrismLibrary/Prism/issues/2099
=> fix(uno-e2e): Disable build fail on android UI tests failure

src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.csproj, src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.csproj
Library layout generation is disabled for Prism.DryIoc.Uno and Prism.Unity.Uno projects as they do not have any XAML files, and that if set to true, there is an nuget issue where Uno.Prism PRI resources get incorrectly propagated to their dependents.
Without this change, a UWP build fails with the following error:
```
error APPX1101: Payload contains two or more files with the same destination path 'Prism.Uno\Prism.Uno.xr.xml'. Source files: 
error APPX1101: C:\Users\XX\.nuget\packages\prism.dryioc.uno\8.0.0.1693-ci\lib\uap10.0.16299\Prism.Uno\Prism.Uno.xr.xml
error APPX1101: C:\Users\XX\.nuget\packages\prism.uno\8.0.0.1693-ci\lib\uap10.0.16299\Prism.Uno\Prism.Uno.xr.xml
```
=> [Uno-UWP] Disable library layout generation

src/Wpf/Prism.Wpf/PrismApplicationBase.cs, src/Wpf/Prism.Wpf/PrismBootstrapperBase.cs, src/Wpf/Prism.Wpf/PrismInitializationExtensions.cs
Reverted the use of the PrismInitializationExtensions.ConfigureViewModelLocator. This actually didn't work properly because we need to access the Container for each view being resolved during the life of the app.
- #2106
=> Fixed ConfigureViewModelLocator implementation

PrismLibrary_Uno.sln, e2e/Uno/HelloUnoWorld.Shared/App.xaml.cs, e2e/Uno/HelloUnoWorld.Shared/HelloUnoWorld.Shared.projitems, e2e/Uno/HelloUnoWorld.Shared/Views/InitialView.xaml, e2e/Uno/HelloUnoWorld.Shared/Views/InitialView.xaml.cs, e2e/Uno/HelloUnoWorld.Shared/Views/Shell.xaml, e2e/Uno/HelloUnoWorld.UITests/Region_Tests.cs, src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs, src/Uno/Prism.Uno/PrismApplicationBase.cs
This change takes into account the fact that the visual tree cannot be navigated until it is loaded, preventing navigation from `PrismApplicationBase.OnInitialized` or `IModule.OnInitialized`. 
This fixes #2102.
No change.
This change implies that `PrismApplicationBase.OnLaunched` and `PrismApplicationBase.OnInitialized` may not be invoked synchronously.
=> [Uno] Adjust the initialization sequence based on tree navigation constraints

src/Forms/Prism.Forms/Prism.Forms.csproj, src/Forms/Prism.Forms/Services/DeviceService.cs, src/Forms/Prism.Forms/Services/IDeviceService.cs, tests/Forms/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj, tests/Forms/Prism.Forms.Tests/Prism.Forms.Tests.csproj, tests/Forms/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Added an async version of "BeginInvokeOnMainThread as detailed here (https://github.com/PrismLibrary/Prism/issues/2043)
I've not written any tests, as I couldn't see any existing tests for that class. I'm happy to write some tests for that class if required, unless I've just missed existing ones.
- Provide links to bugs here
Added:
- Task IDeviceService.BeginInvokeOnMainThreadAsync(Action)
- Task DeviceService.BeginInvokeOnMainThreadAsync(Action)
The developer now has the ability to await Actions invoked on the main thread.
- [x ] Has tests (if omitted, state reason in description)
- [ x] Rebased on top of master at time of PR
- [ x] Changes adhere to coding standard
=> Added a "BeginInvokeOnMainThreadAsync" method to "IDeviceService"

build/scripts/android-uitest-run.sh
Google recently changed their SDK definitions for emulators, where `system-images;android-28;google_apis;x86` became `system-images;android-28;google_apis_playstore;x86`.
This allows for the tests to download the proper emulators.
=> fix: Adjust for updated android SDK Android-28 emulator name

build/steps/prepare-build.yml, src/Uno/Prism.Uno/PrismApplicationBase.cs
Fixes the startup of the application on iOS, caused by the fact that the loaded event on iOS is only raised when Window.Activate() is called.
This PR also restore Uno UI Tests for android, iOS, Wasm platforms.
None.
=> [Uno] Fix iOS startup, restore Uno UI Tests

src/Wpf/Prism.Unity.Wpf/Legacy/UnityBootstrapper.cs, src/Wpf/Prism.Unity.Wpf/Legacy/UnityExtensions.cs, src/Wpf/Prism.Unity.Wpf/PrismApplication.cs, src/Wpf/Prism.Wpf/Bootstrapper.cs, src/Wpf/Prism.Wpf/Common/MvvmHelpers.cs, src/Wpf/Prism.Wpf/Interactivity/CommandBehaviorBase.cs, src/Wpf/Prism.Wpf/Ioc/IContainerRegistryExtensions.cs, src/Wpf/Prism.Wpf/Logging/TextLogger.cs, src/Wpf/Prism.Wpf/Modularity/IModuleCatalogExtensions.cs, src/Wpf/Prism.Wpf/Mvvm/ViewModelLocator.cs, src/Wpf/Prism.Wpf/Regions/Behaviors/DestructibleRegionBehavior.cs, src/Wpf/Prism.Wpf/Regions/IRegionNavigationJournal.cs
Added documentation - issue #1978
Project: Prism.Wpf
None
None
None
=> Added missing XML Docs to various classes in Prism.Wpf

src/Prism.Core/Mvvm/ErrorsContainer.cs, src/Wpf/Prism.DryIoc.Wpf/Legacy/DryIocBootstrapper.cs, src/Wpf/Prism.DryIoc.Wpf/Legacy/DryIocExtensions.cs, src/Wpf/Prism.DryIoc.Wpf/PrismApplication.cs, src/Wpf/Prism.DryIoc.Wpf/PrismBootstrapper.cs, src/Wpf/Prism.Unity.Wpf/PrismBootstrapper.cs
Fixed ErrorsContainer warnings
Added closing </param> tag
Dryloc.WPF & Unity.Wpf
Added PrismApplication/PrismBootstrapper XML comments.
Prism.Wpf is almost free of warnings :)
Resolved Warning when using `<see cref="Dictionary{string, List{T}}" />` in an XML comment
Resolved missing `</param>` tag in ErrorsContainer constructor.
N/A
N/A
=> XML Documentation for Dryloc.Wpf, Unity.Wpf and Prism.Core

src/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.net45.cs, src/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.netcore.cs
Fixed typo in private method name GetNotAllreadyLoadedModuleInfos -> GetNotAlreadyLoadedModuleInfos
Typo in private method name GetNotAllreadyLoadedModuleInfos -> GetNotAlreadyLoadedModuleInfos
Added:
None
Changed:
None
None
=> Fixed spelling error: GetNotAlreadyLoadedModuleInfos

build/azure-pipelines.yml, e2e/Forms/src/HelloRegions/RegionDemoModule.cs, src/Forms/Prism.Forms.Regions/Ioc/RegionNavigationRegistrationExtensions.cs, src/Forms/Prism.Forms.Regions/Regions/Adapters/CollectionViewRegionAdapter.cs, src/Forms/Prism.Forms.Regions/Regions/Adapters/LayoutViewRegionAdapter.cs, src/Forms/Prism.Forms.Regions/Regions/Adapters/ScrollViewRegionAdapter.cs
Fixes issues outlined by @brianlagunas 
Removes the GitHub Packages distribution that suddenly decided to start failing.
- Provide links to bugs here
Changed:
Using the GenericConstraint where T : View
- IContainerRegistry IContainerRegistry.RegisterForNavigation => IContainerRegistry IContainerRegistry.RegisterForRegionNavigation
Changes the LayoutViewRegionAdapter, CollectionViewRegionAdapter (not currently utilized), & the ScrollViewRegionAdapter to provide a basic Region
=> Region fixes

src/Forms/Prism.Forms/Modularity/IModuleCatalogExtensions.cs, src/Forms/Prism.Forms/Modularity/ModuleManager.cs, src/Prism.Core/Modularity/IModuleCatalogCoreExtensions.cs, src/Prism.Core/Modularity/IModuleManager.cs, src/Prism.Core/Modularity/IModuleManagerExtensions.cs, src/Wpf/Prism.Wpf/Modularity/ModuleManager.cs, tests/Forms/Prism.Forms.Tests/Modularity/ModuleManagerExtensionsFixture.cs, tests/Wpf/Prism.Wpf.Tests/Modularity/ModuleManagerExtensionsFixture.cs
Prism previously introduced a number of great extensions off of the IModuleCatalog to check if a Module exists, or is initialized, however in order to validate the current state of a module you must inject both the IModuleManager and IModuleCatalog.
In this scenario it is extremely unlikely that you care at all about the IModuleCatalog and that you only want to be able to load an uninitialized Module. These changes simplify the dependencies you need to handle this simple task.
- resolves #2179
Added:
- IEnumerable<IModuleInfo> IModuleManager.Modules { get; }
IModuleManager Extensions
- bool ModuleExists&lt;T&gt;()
- bool ModuleExists(string name)
- ModuleState GetModuleState&lt;T&gt;()
- ModuleState GetModuleState(string name)
- bool …
=> add ModuleInfo collection to IModuleManager

src/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs, src/Wpf/Prism.Wpf/Services/Dialogs/IDialogServiceExtensions.cs
Added a new virtual method to show the dialog window, and also added new extension methods to show a dialog without parameters
- #2184
Added:
- void IDialogService.Show(name);
- void IDialogService.Show(name, callback);
- void IDialogService.ShowDialog(name);
- void IDialogService.ShowDialog(name, callback);
=> DialogService improvements

README.md, e2e/Wpf/global.json, global.json, src/Forms/Prism.Forms.Regions/Common/MvvmHelpers.cs, src/Forms/Prism.Forms.Regions/Prism.Forms.Regions.csproj, src/Forms/Prism.Forms.Regions/Regions/Navigation/RegionNavigationContentLoader.cs, src/Forms/Prism.Forms/Common/PageUtilities.cs, src/Forms/Prism.Forms/Navigation/PageNavigationService.cs, src/Forms/Prism.Forms/Services/Dialogs/DialogService.cs, src/Prism.Core/Prism.Core.csproj
Aligns the Xamarin.Forms AutowireViewModel behavior with WPF. There is now only a single reference to SetAutowireViewModel in the PageUtilities. This call has been updated to work with all VisualElements instead of just a Page. We now validate that the BindingContext is null AND that the AutowireViewModel Property is null before setting the AutowireViewModel Property.
Additionally adds missing description to the Prism.Forms.Regions package and updates the build SDKs
- n/a
n/a
See Description. We now have an additional check before setting the AutowireViewModel property. This potentially could reduce issues where a ViewModel is being created twice if someone was injecting it into the ctor and setting the BindingContext.
=> Autowire update

src/Containers/Prism.Unity.Shared/UnityContainerExtension.cs, tests/Containers/Prism.Container.Shared/Tests/ContainerFixture.cs, tests/Containers/Prism.Container.Unity.Tests/Prism.Ioc.Unity.Tests.csproj
Reverts changes for Unity to provide support for ResolveAll. This feature will be unsupported on Unity until the issue is addressed in Unity. This won't be until Unity 6 as that is their current effort.
none
Reverts dual registration to provide keyed registration of types for ResolveAll. We will continue to only register it as expected. ResolveAll will not be supported for those using Unity.
=> Unity Updates

src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs, tests/Containers/Prism.Container.DryIoc.Tests/ContainerSetup.cs, tests/Containers/Prism.Container.DryIoc.Tests/ContainerSetupWithDefaultSingleton.cs, tests/Containers/Prism.Container.DryIoc.Tests/ContainerTestsWithDefaultSingleton.cs, tests/Containers/Prism.Container.Shared/Tests/ContainerSetup.cs
Describe your changes here.
The current DryIoc adapter doesn't specify transient reuse scope parameters for registering type, and if containers default reuse rule is changed other than Transient, it doesn't correctly implement the target interfaces contracts.
Also automatic resolution of concrete type is also affected by container default reuse settings.
This is a fix for #2206 
None
After this fix, the containerRegistry.Register call should register type as transient irrespective of the container's default reuse setting. Also. default automatic concrete type resolution always use transient, so any non registered type such as view models are always resolved as transient object.
Note that only with this fix, you can use DryIoc's MefAttribute extension out of the …
=> Fix for Issue 2206 (Register should specify Reuse.Transient explicitly.)

src/Forms/Prism.Forms/Common/ApplicationProvider.cs, src/Forms/Prism.Forms/Common/IApplicationProvider.cs, src/Forms/Prism.Forms/Navigation/INavigationParameters.cs, src/Forms/Prism.Forms/Services/Dialogs/DialogService.cs, src/Forms/Prism.Forms/Services/Dialogs/IDialogParameters.cs, src/Forms/Prism.Forms/Services/Dialogs/IDialogService.cs, src/Forms/Prism.Forms/Services/Dialogs/IDialogServiceExtensions.cs, src/Prism.Core/Common/IParameters.cs, src/Prism.Core/Common/ParametersExtensions.cs
In response to #1978,
Add XML docs for the following interfaces and classes:
- IApplicationProvider
- ApplicationProvider
- IParameters
- IDialogParameters
- IDialogService
- DialogService
- IDialogServiceExtensions
Not much, but a decent icebreaker nonetheless. Love what you guys have done with this project.
None
None
None
=> Add XML Docs to various interfaces and classes

e2e/Uno/HelloUnoWorld.Shared/Dialogs/ConfirmationDialog.xaml, e2e/Uno/HelloUnoWorld.Shared/Dialogs/NotificationDialog.xaml, e2e/Uno/HelloUnoWorld.Shared/Views/ModulesPage.xaml, e2e/Uno/HelloUnoWorld.Shared/Views/Shell.xaml, src/Uno/Prism.Uno/Mvvm/ViewModelLocator.cs, src/Uno/Prism.Uno/Prism.Uno.csproj, src/Wpf/Prism.Wpf/Common/MvvmHelpers.cs
Prism.Wpf had the Autowire improperly cased as AutoWire. This has been fixed for Prism.Uno. We will address a solution for Prism.Wpf in Prism 8.1
Changed:
This change applies only to Prism.Uno
- ViewModelLocator.AutoWireViewModel -> ViewModelLocator.AutowireViewModel
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
=> Normalize ViewModelLocator.AutowireViewModel property name for Uno Platform

src/Forms/Prism.Forms/Navigation/INavigationServiceExtensions.cs
Added back extension methods that were accidentally removed
- #2225
Added:
- `public static Task<INavigationResult> GoBackToRootAsync(this INavigationService navigationService, INavigationParameters parameters = null)`
- `public static Task<INavigationResult> GoBackAsync(this INavigationService navigationService, INavigationParameters parameters = null, bool? useModalNavigation = null, bool animated = true)`
- `public static Task<INavigationResult> NavigateAsync(this INavigationService navigationService, string name, INavigationParameters parameters = null, bool? useModalNavigation = null, bool animated = true)`
- `public static Task<INavigationResult> NavigateAsync(this INavigationService navigationService, …
=> Added back INavigationService extension methods

build/scripts/xcode-update.sh
Apply temporary workaround for Xcode selection for Xamarin.UITest. Reverting this may be needed when running tests on Xcode 12 and later, once Xamarin.UITests supports it (https://github.com/actions/virtual-environments/issues/1932).
=> ci: Apply temporary workaround for https://github.com/actions/virtual-environments/issues/1932

e2e/Forms/src/HelloPageDialog/HelloPageDialogModule.cs, src/Forms/Prism.Forms/Services/PageDialogService/IPageDialogService.cs, src/Forms/Prism.Forms/Services/PageDialogService/PageDialogService.cs
Added `DisplayPromptAsync` to `IPageDialogService`, along with implementation in `PageDialogService`.
None
Added:
- Task<string> IPageDialogService.DisplayPromptAsync();
None
=> Add method to display prompt on IPageDialogService

src/Forms/Prism.Forms/Ioc/IContainerRegistryExtensions.cs
Allows developers to register views with view-models in a non-generic way.
```
/// <summary>
/// Registers a Page for navigation.
/// </summary>
/// <param name="viewType">The Type of Page to register</param>
/// <param name="viewModelType">The Type of ViewModel to use as the BindingContext for the Page</param>
/// <param name="name">The unique name to register with the Page</param>
/// <param name="containerRegistry"></param>
public static void RegisterForNavigation(this IContainerRegistry containerRegistry, Type viewType, Type viewModelType, string name = null)
```
=> Non-generic register for navigation with view-model

src/Forms/Prism.Forms/Common/PageUtilities.cs
Added a check for the VML to automatically apply to views whose binding context is the same as the parent, which indicates it was inherited.
- #2279
none
Views
=> Automatically apply VML to view with same binding context as parent

src/Wpf/Prism.Wpf/Services/Dialogs/Dialog.cs
Removed default value for Dialog.WindowStartupLocation
- #2216
Custom Dialog WIndows can now work properly with the attached property
=> Fixed default value for WindowStartupLocation

src/Forms/Prism.Forms/Navigation/PageNavigationService.cs
Makes the SetNavigationServiceForPage method in the PageNavigationService protected. This ensures that those providing a custom implementation of the PageNavigationService can call this method if they have some crazy custom logic for creating Pages.
=> Make SetNavigationServiceForPage protected

Directory.Build.props, e2e/Forms/src/HelloPageDialog/HelloPageDialogModule.cs, e2e/Forms/src/HelloPageDialog/ViewModels/ActionSheetDemoPageViewModel.cs, e2e/Forms/src/HelloPageDialog/ViewModels/AlertDialogDemoPageViewModel.cs, e2e/Forms/src/HelloPageDialog/ViewModels/DisplayPromptDemoPageViewModel.cs, e2e/Forms/src/HelloPageDialog/ViewModels/PageDialogDemoBaseViewModel.cs, e2e/Forms/src/HelloPageDialog/Views/ActionSheetDemoPage.xaml, e2e/Forms/src/HelloPageDialog/Views/ActionSheetDemoPage.xaml.cs, e2e/Forms/src/HelloPageDialog/Views/AlertDialogDemoPage.xaml, e2e/Forms/src/HelloPageDialog/Views/AlertDialogDemoPage.xaml.cs, e2e/Forms/src/HelloPageDialog/Views/DisplayPromptDemoPage.xaml, e2e/Forms/src/HelloPageDialog/Views/DisplayPromptDemoPage.xaml.cs, e2e/Forms/src/HelloPageDialog/Views/PageDialogTabs.cs, e2e/Forms/src/HelloWorld/App.xaml.cs, e2e/Forms/src/HelloWorld/Views/MyMasterDetail.xaml, src/Forms/Prism.Forms/AppModel/FlowDirection.cs, src/Forms/Prism.Forms/AppModel/IKeyboardMapper.cs, src/Forms/Prism.Forms/AppModel/KeyboardMapper.cs, src/Forms/Prism.Forms/AppModel/KeyboardType.cs, src/Forms/Prism.Forms/Navigation/NavigationMode.cs, src/Forms/Prism.Forms/Navigation/Xaml/Navigation.cs, src/Forms/Prism.Forms/PrismApplicationBase.cs, src/Forms/Prism.Forms/Services/DeviceService.cs, src/Forms/Prism.Forms/Services/IDeviceService.cs, src/Forms/Prism.Forms/Services/PageDialogService/IPageDialogService.cs, src/Forms/Prism.Forms/Services/PageDialogService/PageDialogService.cs, tests/Forms/Prism.Forms.Tests/Mocks/PageDialogServiceMock.cs, tests/Forms/Prism.Forms.Tests/Services/PageDialogServiceFixture.cs
Updates the PageDialogService with additional newer methods that accommodate for the text FlowDirection. Updates the E2E PageDialogService Module to have various pages to explore the Alert, ActionSheet and Prompt API's.
The API's have also been updated to get rid of things in the Xamarin.Forms namespace as we don't want people breaking MVVM with references to UI in their ViewModel. Also addresses bug with TabbedNavigation as this was directly affecting the updated E2E updates.
- #2316
- #2218, #2295, #2317
Added:
- IKeyboardMapper -> Keyboard Map(KeyboardType)
- KeyboardType enum
- FlowDirection
- Task<bool> IPageDialogService.DisplayAlertAsync(string title, string message, string acceptButton, string …
=> PageDialogService Updates

.gitignore, .vscode/extensions.json, .vscode/settings.json, build/azure-pipelines.yml, build/jobs/e2e-ios.yml, build/nuget.config, build/steps/prepare-build.yml, build/steps/publish-vstest-results.yml, e2e/Forms/src/HelloWorld.Android/MainActivity.cs, e2e/Forms/src/HelloWorld/App.xaml.cs, src/Forms/Prism.Forms/Common/PageUtilities.cs, src/Forms/Prism.Forms/Navigation/PageNavigationService.cs, src/Forms/Prism.Forms/Prism.Forms.csproj, src/Forms/Prism.Forms/PrismPlatform.cs, src/Forms/Prism.Forms/Services/Dialogs/DialogPage.cs, src/Forms/Prism.Forms/Services/Dialogs/DialogService.cs, src/Forms/Prism.Forms/Services/Dialogs/IDialogContainer.cs
This PR adds support to optionally handle the Android "Hardware" go back.  As there is no actual hook in Xamarin.Forms itself to handle this from an X-Plat standpoint. No tests added as this is largely platform specific, also I'm lazy and want to give Brian something to complain about while doing a live stream....
- #1862
Added:
- Static PrismPlatform class is now available on Android only. This exposes an async OnBackPressed method that will handle either going back for Dialogs or Pages on the NavigationStack.
- IBackPressedResult - this is an annoying yet necessary layer as we have different result types for Dialogs and Navigation.
- IDialogContainer - this provides some additional surface area to allow Prism to dismiss Dialogs with the hardware back, and makes …
=> Handle Android Hardware GoBack

src/Forms/Prism.Forms/Ioc/ContainerProvider.cs, src/Forms/Prism.Forms/Services/Dialogs/Xaml/ShowDialogExtension.cs
Updates references to the Container to be in line with Prism 8's ContainerLocator instead of referencing the static instance of the PrismApplication
- None (housekeeping)
none
none
=> use ContainerLocator

src/Forms/Prism.Forms/Xaml/ParentPageAwareExtension.cs, src/Forms/Prism.Forms/Xaml/TargetBindingContext.cs
Fixes bug with the Binding Context of the ParentPageAwareExtension base XAML Extension setting the BindingContext to the Parent Page's Binding Context instead of the Target Element's Binding Context.
- fixes #2232
Adds TargetBindingContext enum. To use the legacy behavior of targeting the Page's BindingContext simply set this property. By default it will use the TargetElement.
Navigation XAML Extensions & Dialog XAML Extension now correctly set the BindingContext of the Command / Extension to the Target Element's Binding Context instead of the Page's Binding Context. This correctly supports uses within Lists.
=> Use the Target Element BindingContext instead of the Page VM

src/Wpf/Prism.Wpf/Regions/RegionManager.cs
Implement the support for `RegionManager.IsInDesignMode`
- fixes #2418
None
This will indicate prism to stop processing regions when hosted in the XAML designed.
=> fix: [UWP][WinUI] Support for `RegionManager.IsInDesignMode`

src/Forms/Prism.Forms.Regions/Common/MvvmHelpers.cs, src/Wpf/Prism.Wpf/Regions/RegionViewRegistry.cs, tests/Wpf/Prism.Wpf.Tests/Mocks/ViewModels/MockOptOutViewModel.cs, tests/Wpf/Prism.Wpf.Tests/Mocks/Views/MockOptOut.cs, tests/Wpf/Prism.Wpf.Tests/Mvvm/ViewModelLocatorFixture.cs, tests/Wpf/Prism.Wpf.Tests/Regions/RegionViewRegistryFixture.cs
Automatically applies the AutowireViewModel when using RegisterViewWithRegion
- #2236
- None
When using RegisterVIewWithRegion, you are no longer required to use the ViewModelLocator.AutowireViewModel attached property. It is now on by default.
=> Apply AutowireViewModel automatically when using RegisterVIewWithRegion

src/Forms/Prism.Forms/Xaml/ParentPageAwareExtension.cs, tests/Forms/Prism.DI.Forms.Tests/Fixtures/Navigation/XamlNavigationFixture.cs
Added support for the NavigateTo markup extension to work within the Prism EventToCommandBehavior. You can now do something like this:
```
<ListView ItemsSource="{Binding Authors}">
<ListView.Behaviors>
<prism:EventToCommandBehavior EventName="ItemTapped"
Command="{prism:NavigateTo 'AuthorDetailPage'}"
EventArgsParameterPath="Item" />
</ListView.Behaviors>
</ListView>
```
- #2484
NONE
NavigateTo now works with the EventToCommandBehavior
=> Add Support for NavigateTo within EventToCommandBehavior

README.md
@dansiegel and I were talking about the Popup Plugin that I open sourced and thought it would be a good idea to add our Popup Plugin to the readme so other community members can easily find it. [FileOnQ.Prism.Popups.XCT](https://github.com/FileOnQ/Prism.Popups.XCT) adds support for the Xamarin Community Toolkit native popups.
This PR updates the readme only no code changes to project.
Open to any changes that need to be made to the Readme to ensure the community plugin is communicated correctly.
N/A
N/A
N/A
=> Adds FileOnQ.Prism.Popups.XCT Community Plugin to Readme

e2e/Uno/ModuleA/ModuleA.WinUI.csproj, src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.WinUI.csproj, src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.WinUI.csproj, src/Uno/Prism.Uno/Prism.Uno.WinUI.csproj
Reunion 0.8 uses the TargetFramework verbatim to package additional content, which is different from what nuget infers.
Using `net5.0-windows10.0.18362.0` is transformed to `net5.0-windows10.0.18362` by nuget, but the mrt packaging still uses `net5.0-windows10.0.18362.0` causing a build failure where some resource files cannot be found.
Added: None 
Changed: None
None
=> fix: Adjust net5.0 targetframework to fix assets packaging

src/Wpf/Prism.Wpf/Common/MvvmHelpers.cs
Changed the access modifier of the AutowireViewModel method from internal to public in the MvvmHelpers class and added documentation.
- #2522 
Changed:
- internal static void  AutowireViewModel => public static void AutowireViewModel
Developers can now access this method from an external assembly.
=> Changed the access modifier of the AutowireViewModel method to public

src/Prism.Core/Events/WeakDelegatesManager.cs
Added XmlDoc for WeakDelegatesManager.cs
I opened the PrismLibrary_Wpf.sln solution and this was the only file with XmlDoc warnings.
Should I add an example element?
No code/behavior change.
=> XmlDoc for WeakDelegatesManager

version.json
As discussed in issue #2683 the Prism Library has left the .NET Foundation. As a result of this the official License Holder has changed from the .NET Foundation to the Prism Library team. While Prism will continue to ship under the MIT License we are bumping major versions to help better mark that a significant change has occurred.
=> bump to 9.0

global.json, src/Prism.Core/Prism.Core.csproj, src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.WinUI.csproj, src/Uno/Prism.Uno/Prism.Uno.WinUI.csproj, src/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj, src/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj, src/Wpf/Prism.Wpf/Prism.Wpf.csproj
Bumps from net5 to net6. Deprecates target for netcoreapp3.1
=> bump to net6

src/Forms/Prism.Forms/Services/Dialogs/DialogResult.cs, src/Forms/Prism.Forms/Services/Dialogs/IDialogResult.cs
Add Missing XML Docs To IDialogResult and DialogResult.
I refer to [PrismLibrary_Wpf  comment](https://github.com/PrismLibrary/Prism/blob/master/src/Wpf/Prism.Wpf/Services/Dialogs/IDialogResult.cs).
I only add missing XML Docs so I omitted tests.
- #1978 
None.
None.
=> Update IDialogResult and DialogResult

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ViewModels/MockViewModelBase.cs
Fixes bug where navigation stack starting with `/NavigationPage/ViewA/ViewB` with navigation to `ViewC/ViewD` would end up with `/NavigationPage/ViewA/ViewC/ViewB/ViewD`
- closes #2832
none
Fixes bug with insert before logic with Navigation Page
=> fix: Navigation inserts page before current page in NavigationPage stack

src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs, tests/Containers/Prism.Container.Shared/Tests/ContainerFixture.cs
Fixing missing Reuse for transient factory registrations
- closes #2802
n/a
adds missing Reuse.Transient for Factory registrations on DryIoc
=> Transient factory

src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs, src/Containers/Prism.Unity.Shared/UnityContainerExtension.cs, src/Prism.Core/Ioc/ContainerResolutionException.cs, tests/Forms/Prism.Forms.Regions.Tests/Tests/LocatorNavigationTargetHandlerFixture.cs
This updates the ContainerResolutionException to take the IContainerProvider as an argument. This ensures that when GetErrors is called it will make use of the current scope rather than attempting to use the root container.
- ContainerResolutionException.GetErrors uses root container
- n/a
ContainerResolutionException will now use the scoped instance of the ContainerProvider that was used when the exception was thrown rather than falling back to the Root.
=> Use instance of IContainerProvider to resolve dependencies

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs
There was a fallback to `true` for `useModalNavigation` if no other value was specified. This broke the FlyoutPage navigation (and maybe other things as well).
I added a new test that fails without my changes and succeeds with my changes.
- fixes #2820 
n/a
`useModalNavigation` is now correctly calculated
=> Fix MAUI flyout navigation

e2e/Maui/PrismMauiDemo.sln, src/Maui/Prism.Maui/Behaviors/MultiPageActiveAwareBehavior.cs, src/Maui/Prism.Maui/Behaviors/NavigationPageActiveAwareBehavior.cs, src/Maui/Prism.Maui/Extensions/CollectionExtensions.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Behaviors/NavigationBehaviors.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ViewModels/MockViewModelBase.cs
This updates the behaviors to help ensure that we do not accidently mark a View/ViewModel as active when it technically is not. For instance in the case where a NavigationPage is child of a TabbedPage. The NavigationPage may not be the active tab of the TabbedPage while the CurrentPage of the NavigationPage will still be marked as active.
This ensures that all children of the NavigationPage are in fact not active in this scenario.
- closes #2816 
n/a
Adds additional checks before setting IActiveAware.IsActive
=> IActiveAware activates inactive views

.github/workflows/build_core.yml, .github/workflows/build_forms.yml, .github/workflows/build_maui.yml, .github/workflows/build_uno.yml, .github/workflows/build_wpf.yml, src/Prism.Events/EventAggregator.cs
Adds a static Current instance of the EventAggregator. This is useful for scenarios when working in native code where you may not have easy access to CI however you need to publish or subscribe to events.
- n/a
Added:
- static IEventAggregator Current { get; set; }
n/a
=> EA add static instance

src/Maui/Prism.Maui/Mvvm/ViewModelLocator.cs
Fixed runtime output window warning "Microsoft.Maui.Controls.BindableObject: Warning: Cannot convert True to type 'Prism.Mvvm.ViewModelLocatorBehavior'"
Replaced old "True" with new "ViewModelLocatorBehavior.Automatic" when setting AutowireViewModel property.
N/A
No more warning
=> Fixing runtime warning

e2e/Maui/PrismMauiDemo.sln, src/Maui/Prism.Maui/Common/MvvmHelpers.cs, src/Maui/Prism.Maui/Controls/PrismNavigationPage.cs, src/Maui/Prism.Maui/Navigation/PrismWindow.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs
Fixes handler for the BackButton on Android
Describe your changes here.
- closes #2815 
- closes #2814
=> Fix Android Back Button

src/Prism.Core/Commands/DelegateCommand.cs, src/Prism.Core/Commands/DelegateCommandBase.cs, src/Prism.Core/Commands/DelegateCommand{T}.cs, src/Prism.Core/Common/MulticastExceptionHandler.cs, tests/Prism.Core.Tests/Commands/DelegateCommandFixture.cs, tests/Prism.Core.Tests/Common/MulticastExceptionHandlerFixture.cs
This adds a MulticastExceptionHandler. This allows some flexibility in being able to provide more dynamic types which includes the ability to specify strongly typed Exception handlers for specific Exception types.
- closes #2873
Adds public API's to the DelegateCommand for `Catch<TException>`
When a Catch is specified this will attempt to catch any exception thrown during the execution of the command. If no delegate is registered for it, it will rethrow the exception.
**NOTE** for `DelegateCommand<T>` the protected implementation has been updated to no longer call the `Execute(T parameter)` and instead now will simply call the delegate directly. This is because we need to also allow developers to catch an InvalidCastException in the event that the UI Framework …
=> Adding Exception Handler

Directory.Packages.props, src/Maui/Prism.Maui/Prism.Maui.csproj
- feat: net8 support dropping PrismApplication
- fix: fixed build on net8
I never imagined this day would come, look at me doing a PR to Prism, lol.
On .net8 Maui packages are shipped as nuget packages and not on workloads, so you need add those explicity on your central package version management.
Build didn't work, @dansiegel knew it
=> Adding Maui packages to the nuget central package version management

src/Prism.Core/Commands/AsyncDelegateCommand.cs, src/Prism.Core/Commands/AsyncDelegateCommand{T}.cs, src/Prism.Core/Commands/DelegateCommandBase.cs, src/Prism.Core/Commands/IAsyncCommand.cs, tests/Prism.Core.Tests/Commands/AsyncDelegateCommandFixture.cs
Adding support for an AsyncDelegateCommand. By default this will prevent simultaneous execution of the Task. This behavior can be opted out of by calling the `EnableParallelExecution()` method on the AsyncDelegateCommand. Note that we will suppress the `TaskCanceledException` to prevent this from being raised when a CancellationToken cancels the Task.
```cs
// Parameterless Callback
var cmd1 = new AsyncDelegateCommand(Command1);
Task Command1() => Task.Delay(500);
// Callback with a CancellationToken
var cmd2 = new AsyncDelegateCommand(Command2);
Task Command2(CancellationToken token) => Task.Delay(500, token);
// Callback with our Generic model type
var cmd3 = new AsyncDelegateCommand<MyModel>(Command3);
Task Command3(MyModel model) => Task.Delay(500);
// …
```
=> Adding AsyncDelegateCommand

LICENSE
Updates project license. Prism is now dual licensed. Those organizations earning more than $1,000,000 USD / year should [reach out](https://avantipoint.com/contact) to obtain a license.
=> Update to dual license

src/Forms/Prism.Forms/PrismApplicationBase.cs, src/Maui/Prism.Maui/Ioc/RegionNavigationRegistrationExtensions.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, src/Prism.Core/Ioc/IContainerRegistryExtensions.cs, src/Wpf/Prism.Wpf/PrismInitializationExtensions.cs, tests/Containers/Prism.Container.Shared/Tests/ContainerFixture.cs
Adding TryRegister API for the container. This will avoid re-registering services which have already been registered.
Added:
- IContainerRegistry TryRegister<T>()
- IContainerRegistry TryRegisterScoped<T>()
- IContainerRegistry TryRegisterSingleton<T>()
- IContainerRegistry TryRegister<TFrom, TTo>()
- IContainerRegistry TryRegisterScoped<TFrom, TTo>()
- IContainerRegistry TryRegisterSingleton<TFrom, TTo>()
- IContainerRegistry TryRegisterInstance<T>(T instance)
Prism will now internally call TryRegister
=> Adding TryRegister

src/Prism.Core/Commands/AsyncDelegateCommand.cs, src/Prism.Core/Commands/AsyncDelegateCommand{T}.cs, src/Prism.Core/Commands/CompositeCommand.cs, src/Prism.Core/Commands/DelegateCommand.cs, src/Prism.Core/Commands/DelegateCommandBase.cs, src/Prism.Core/Commands/DelegateCommand{T}.cs, src/Prism.Core/Commands/PropertyObserver.cs, src/Prism.Core/Commands/PropertyObserverNode.cs
I have also taken the opportunity to apply the features of new versions of C#.
I have concerns on how to act on the AsyncDelegateCommand when casting. I have chosen to use ! (null-forgiving) but I want your opinion.
=> Add nullable annotations to commands

src/Wpf/Prism.Wpf/Properties/AssemblyInfo.cs
Removes legacy XmlnsDefinitionAttribute's. `http://www.codeplex.com/prism` namespace will no longer be valid for WPF applications. Namespaces should be updated to use `http://prismlibrary.com/`
=> Remove legacy xmlns namespaces

Directory.Packages.props, e2e/Uno/HelloWorld.Mobile/HelloWorld.Mobile.csproj, e2e/Uno/HelloWorld.Skia.Gtk/HelloWorld.Skia.Gtk.csproj, e2e/Uno/HelloWorld.Skia.Linux.FrameBuffer/HelloWorld.Skia.Linux.FrameBuffer.csproj, e2e/Uno/HelloWorld.Skia.WPF/HelloWorld.Skia.WPF.csproj, e2e/Uno/HelloWorld.Wasm/HelloWorld.Wasm.csproj, e2e/Uno/HelloWorld.Windows/HelloWorld.Windows.csproj, e2e/Uno/HelloWorld/HelloWorld.csproj, e2e/Uno/ModuleA/Dialogs/AlertDialog.xaml, e2e/Uno/ModuleA/Dialogs/AlertDialog.xaml.cs, e2e/Uno/ModuleA/Dialogs/AlertDialogViewModel.cs, e2e/Uno/ModuleA/ModuleA.csproj, e2e/Uno/ModuleA/ModuleAModule.cs, e2e/Uno/ModuleA/ViewModels/ViewAViewModel.cs, e2e/Uno/ModuleA/ViewModels/ViewBViewModel.cs, e2e/Uno/ModuleA/ViewModels/ViewModelBase.cs, e2e/Uno/ModuleA/Views/ViewA.xaml, src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.WinUI.csproj, src/Uno/Prism.Uno/Prism.Uno.WinUI.csproj, src/Wpf/Prism.Wpf/Dialogs/IDialogServiceCompatExtensions.cs
This updates Uno to build against Uno 5.0 currently in preview. This adds a Dialog sample to the Uno e2e app, and fixes an ambiguous reference issue with dialog extensions that are now in Core.
=> Uno 5 update

.github/workflows/start-release.yml, Directory.Build.props, Directory.Build.targets, build/consolidate-artifacts.ps1
Deprecates publishing the binaries. This really isn't needed with NuGet packages already being released. This should fix the package signing issue that prevented Prism.Events from getting published.
- closes #2973
=> fixing release paths

src/Uno/Prism.Uno/Dialogs/DialogService.cs, src/Uno/Prism.Uno/Dialogs/DialogWindow.xaml.cs, src/Uno/Prism.Uno/Dialogs/IDialogWindow.cs, src/Uno/Prism.Uno/PrismApplicationBase.cs, src/Wpf/Prism.Wpf/Dialogs/KnownDialogParameters.cs
This fixes an exception encountered in the DialogService on WinUI by setting the XamlRoot. 
- Caused by https://github.com/microsoft/microsoft-ui-xaml/issues/3678
=> Fix DialogService - Setting XamlRoot

e2e/Uno/HelloWorld/Views/Shell.xaml, src/Uno/Prism.Uno/Navigation/Regions/NavigationViewRegionAdapter.cs, src/Wpf/Prism.Wpf/PrismInitializationExtensions.cs
Adding Region Adapter for the NavigationView for Uno Platform. This allows you to simply provide a UI like:
```xml
<NavigationView prism:RegionManager.RegionName="ContentRegion"
IsSettingsVisible="false">
<NavigationView.MenuItems>
<NavigationViewItem Content="View A" Tag="ViewA" />
<NavigationViewItem Content="View B" Tag="ViewB" />
</NavigationView.MenuItems>
</NavigationView>
```
=> Add NavigationView RegionAdapter

src/Prism.Core/Commands/AsyncDelegateCommand.cs, src/Prism.Core/Commands/AsyncDelegateCommand{T}.cs, tests/Prism.Core.Tests/Commands/AsyncDelegateCommandFixture.cs
Adds various minor fixes for AsyncDelegateCommand
- Adds new CancelAfter(TimeSpan) method to set the CancelationToken Factory to provide a Token that will expire after a specified TimeSpan
- Adds additional check in the Execute to ensure if Parallel Execution is disabled that we do not execute while IsExecuting is true. This will automatically cancel the additional request.
- Sets ConfigureAwait on the Delegate to false as the Command should not need to return to the calling thread.
- Uses WaitAsync(CancelationToken) when running in net6+ for delegates that do not directly provide a CancelationToken
=> AsyncDelegateCommand enhancements

e2e/Uno/HelloWorld/Views/Shell.xaml, src/Uno/Prism.Uno/Dialogs/DialogService.cs, src/Uno/Prism.Uno/Dialogs/DialogWindow.xaml.cs, tests/Prism.Core.Tests/Commands/AsyncDelegateCommandFixture.cs
Removing the strong dependency on the Window in the DialogWindow. This now has shifted to set the XamlRoot from the DialogService if the IDialogWindow is a ContentDialog.
=> Remove Window dependency in DialogWindow

src/Maui/Prism.Maui/PrismAppBuilderExtensions.cs
Add App Action helpers for Prism. This helps shortcut some of the overhead that you would need when trying to provide a callback such as ensuring this runs on the UI Thread, getting the `INavigationService` and optionally also the `IContainerProvider` if you need to resolve additional services as part of the App Action callback.
- n/a
Added:
- static PrismAppBuilder ConfigureViewTypeToViewModelTypeResolver(this PrismAppBuilder builder, Func<Type, Type> viewModelTypeResolver)
- static PrismAppBuilder RegisterAppAction(this PrismAppBuilder builder, AppAction appAction, Func<IContainerProvider, INavigationService, AppAction, Task> callback)
- static PrismAppBuilder RegisterAppAction(this PrismAppBuilder builder, AppAction appAction, Func<INavigationService, …
=> Add AppAction registration helpers.

Directory.Packages.props, e2e/Uno/HelloWorld.Mobile/HelloWorld.Mobile.csproj, e2e/Uno/HelloWorld.Skia.Gtk/HelloWorld.Skia.Gtk.csproj, e2e/Uno/HelloWorld.Skia.Linux.FrameBuffer/HelloWorld.Skia.Linux.FrameBuffer.csproj, e2e/Uno/HelloWorld.Skia.WPF/HelloWorld.Skia.WPF.csproj, e2e/Uno/HelloWorld.Wasm/HelloWorld.Wasm.csproj, e2e/Uno/HelloWorld.Windows/HelloWorld.Windows.csproj, e2e/Uno/HelloWorld/App.cs, e2e/Uno/HelloWorld/HelloWorld.csproj, src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, src/Uno/Prism.Uno/PrismApplicationBase.cs
Provide new Configure Window method in PrismApplicationBase to make an easier to understand API where you might need to configure things with the Window such as enabling HotReload.
- Updates to latest Uno patch releases
- Updates to SourceLink v8.0
- n/a
Added:
- void PrismApplicationBase.ConfigureWindow(Window);
n/a
=> Provide ConfigureWindow for Uno

Directory.Packages.props, PrismLibrary.sln, PrismLibrary_Uno.slnf, src/Directory.Build.props, src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.WinUI.csproj, src/Uno/Prism.Uno.Markup/AssemblyInfo.cs, src/Uno/Prism.Uno.Markup/Prism.Uno.WinUI.Markup.csproj, src/Uno/Prism.Uno/Prism.Uno.WinUI.csproj
Adds new package for C# Markup support for Uno Platform
- n/a
Adds generated C# Markup extensions to make it easier when building Prism applications with Uno Platform and C# Markup. This will allow developers to leverage attached properties within Prism such as the ViewModelLocator to easily set the Autowire property from code.
=> Adding support for C# Markup

.github/workflows/build_uno.yml, .github/workflows/ci.yml, .vscode/extensions.json, Directory.Build.props, PrismLibrary.sln, src/Directory.Build.props
Bumps install version of .NET to net8.0 for Uno builds
=> Use net8 for Uno CI build

e2e/Maui/PrismMauiDemo/MauiProgram.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, src/Maui/Prism.Maui/PrismAppBuilderExtensions.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Behaviors/NavigationBehaviors.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/DynamicTabbedPageNavigationFixture.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Regions/RegionFixture.cs
To better align with what Prism/.NET MAUI are doing, the `PrismAppBuilder` method `OnAppStart` is being renamed to `CreateWindow`. This better aligns with where .NET MAUI actually is ultimately invoking the Prism delegate to do the initial navigation and should make the API clearer in aligning with the appropriate method naming used by .NET MAUI
- n/a
Changed:
- PrismAppBuilder.OnAppStart -> PrismAppBuilder.CreateWindow
none
=> BREAKING: Change OnAppStart to CreateWindow

src/Maui/Prism.Maui/Navigation/INavigationService.cs, src/Maui/Prism.Maui/Navigation/INavigationServiceExtensions.cs, src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ViewModels/MockViewModelBase.cs
In Prism.Forms you had the ability to select the tab from another tab. This isn't quite possible to do from an Extension method now that we've removed IPageAware. This has now been added as an API on INavigationService itself.
- n/a
Added:
- Task<INavigationResult> INavigationService.SelectTabAsync(INavigationParameters);
=> Adding select tab API to INavigationService

src/Maui/Prism.Maui/Mvvm/ViewModelLocator.cs, src/Maui/Prism.Maui/Mvvm/ViewRegistryBase.cs, src/Maui/Prism.Maui/Navigation/PrismWindowManager.cs, src/Maui/Prism.Maui/Navigation/Xaml/Navigation.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, src/Maui/Prism.Maui/PrismAppBuilderExtensions.cs, src/Prism.Core/Mvvm/ViewRegistryBase{TBaseView}.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Regions/RegionFixture.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/TestBase.cs
Small code cleanup/refactorings
Adding additional XML docs for PrismAppBuilder APIs
Adding additional tests for RegionManger to ensure Regions are properly cleaned up when Pages are navigated away from.
=> Maui Cleanup

e2e/Maui/Directory.Build.targets, e2e/Uno/Directory.Build.targets, src/Prism.Core/build/Package.targets, src/Prism.Events/build/Package.targets, src/Wpf/Prism.DryIoc.Wpf/build/Package.targets, src/Wpf/Prism.Unity.Wpf/build/Package.targets, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/TestBase.cs
Adds targets to Prism.DryIoc and Prism.Unity to provide implicit namespace support for their implementation of PrismApplication.
Moves using from Prism.Core to the Prism.Events package for the Prism.Events namespace. This will provide implicit namespace support for Prism.Events even if you don't reference Prism.Core.
- missing implicit namespaces
none
implicit namespaces are now supported for Prism.Unity and Prism.DryIoc
=> Adding implicit namespaces for DI packages

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs
Extracted the navigation of `GoBackAsync `into a new method `GoBackInternalAsync`.
`GoBackAsync` will wait for the semaphore and call `GoBackInternalAsync`.
`RemoveAndGoBack` calls `GoBackInternalAsync` to prevent a deadlock during navigation.
#3047 
None
N/a
=> Navigation RemovePageInstruction not working correctly

src/Maui/Prism.Maui/Mvvm/ViewModelLocator.cs, src/Maui/Prism.Maui/Mvvm/ViewModelLocatorBehavior.cs, src/Maui/Prism.Maui/Navigation/Xaml/Navigation.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ViewModels/ForcedViewModel.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Views/ForcedView.cs
Adds Forced Behavior for ViewModelLocation
- n/a
Added:
- ViewModelLocationBehavior.Forced
This restores the expected behavior from Xamarin.Forms where the ViewModel is immediately resolved. This is NOT recommended for most scenarios as you will likely not get the proper Container Scope.
=> feat: adding Forced option for ViewModelLocationBehavior

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs
Ensures that we merge the provided INavigationParameters with the segment parameters
- closes #2956
none
scenarios where navigation parameters were missing will not have the expected parameters
=> Merge parameters for segments

src/Maui/Prism.Maui/PrismAppBuilder.cs, src/Maui/Prism.Maui/Services/PageDialogs/PageDialogService.cs
Refactor the IPageDialogService so it can be registered and used as a Singleton throughout the application.
- requested feature from Commercial Plus Discord
n/a
The IPageDialogService is no longer registered as a scoped service.
=> Make IPageDialogService a Singleton

src/Maui/Prism.Maui/Common/MvvmHelpers.cs, src/Maui/Prism.Maui/Controls/PrismNavigationPage.cs, src/Maui/Prism.Maui/Prism.Maui.csproj
Added an additional check when `PrismNavigationPage` is dismissed for the following conditions:
- Is the page using a non default value for `ModalPresentationStyle`?
- Is the navigation source `Device`?
If both are true, the navigation service will call go back (modal) once, to ensure that the prism navigation service stack matches the true page stack of the maui app.
- #3071 
Added:
None
Changed:
None
There should be no behavioural changes
Currently there are no tests for the change in functionality, I can add them if you think they would be useful
=> Fix unhandled dismissal of iOS modals

src/Maui/Prism.Maui/AppModel/IApplicationLifecycleAware.cs, src/Maui/Prism.Maui/AppModel/IPageLifecycleAware.cs, src/Maui/Prism.Maui/Behaviors/MultiPageActiveAwareBehavior.cs, src/Maui/Prism.Maui/Behaviors/NavigationPageActiveAwareBehavior.cs, src/Maui/Prism.Maui/Behaviors/PageLifeCycleAwareBehavior.cs, src/Maui/Prism.Maui/Behaviors/PageScopeBehavior.cs, src/Maui/Prism.Maui/Behaviors/TabbedPageActiveAwareBehavior.cs, src/Maui/Prism.Maui/Dialogs/DialogViewRegistry.cs, src/Maui/Prism.Maui/Dialogs/IDialogViewRegistry.cs, src/Maui/Prism.Maui/Dialogs/KnownDialogParameters.cs, src/Maui/Prism.Maui/Dialogs/Xaml/DialogLayout.cs, src/Prism.Core/Common/MulticastExceptionHandler.cs, src/Prism.Core/Mvvm/ViewCreationException.cs, src/Prism.Core/Mvvm/ViewModelCreationException.cs, src/Prism.Core/Mvvm/ViewRegistration.cs, src/Prism.Core/Mvvm/ViewRegistryBase{TBaseView}.cs, src/Prism.Core/Mvvm/ViewType.cs, src/Prism.Core/Navigation/Regions/IRegionNavigationRegistry.cs, src/Prism.Core/Navigation/Regions/ViewRegistrationException.cs
Adding missing XML docs across Prism.Core and Prism.Maui
=> Missing XML Docs

src/Maui/Prism.Maui/Dialogs/DialogService.cs, src/Maui/Prism.Maui/Dialogs/IDialogContainer.cs, src/Maui/Prism.Maui/Dialogs/RelativeContentSizeConverter.cs, src/Maui/Prism.Maui/Navigation/PrismWindow.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs
Removes Application.Quit() on the Android back from the Root page. Adds logic to handle back request when a Dialog is displayed.
- fixes #3018
- fixes #2990
Added:
- static IList<IDialogContainer> DialogStack { get; } (IDialogContainer)
=> Fixes for Android Back

src/Maui/Prism.Maui/Common/MvvmHelpers.cs, src/Maui/Prism.Maui/Dialogs/DialogService.cs, src/Maui/Prism.Maui/Dialogs/DialogServiceBase.cs, src/Maui/Prism.Maui/Dialogs/SingletonDialogService.cs, src/Maui/Prism.Maui/Navigation/IWindowManager.cs, src/Maui/Prism.Maui/Navigation/IWindowManagerExtensions.cs, src/Maui/Prism.Maui/Navigation/PrismWindow.cs, src/Maui/Prism.Maui/Navigation/PrismWindowManager.cs, src/Maui/Prism.Maui/Services/PageDialogs/PageDialogService.cs
Add APIs to make it easier to access IDialogService within a Singleton
=> [Enhancement] Make it easier to access IDialogService from Singletons

src/Maui/Prism.Maui/Navigation/Builder/INavigationBuilder.cs, src/Maui/Prism.Maui/Navigation/Builder/NavigationBuilder.cs, src/Maui/Prism.Maui/Navigation/Builder/NavigationBuilderExtensions.cs, src/Maui/Prism.Maui/Navigation/INavigationService.cs, src/Maui/Prism.Maui/Navigation/INavigationServiceExtensions.cs, src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs
With #2818 the behavior of `GoBack` was extended to support navigating back to a specific `viewName` in the stack.
But there is currently no generic version of GoBack in the `NavigationBuilder`.
This PR adds the generic `GoBack<TViewModel>()` to the `NavigationBuilder`.
As suggested by [dansiegel](https://github.com/PrismLibrary/Prism/pull/3101#discussion_r1538450909) I have removed the legacy  `GoBackTo<TViewModel>()` instead of marking it as obsolete.
The old `GoBackTo` worked differently and popped each page and called `CanNavigateAsync`, `OnNavigatedFrom`, and `OnNavigatedTo` of each page. Maybe there are cases when this is the desired behavior. So if you want to keep the old behavior, I suggest giving this methods a clear name to easily distinguish `GoBack` …
=> Add generic GoBack and remove legacy GoBackTo

README.md
Updated README.md's broken link to the Prism website's documentation.
I apologize for not creating an issue for this first. If need be, I can do so for formality.
- The link would resolve to a 404 Not Found
None
Changed:
- The ReadMe link previously pointed to `https://prismlibrary.com/docs/` which it is now, `https://docs.prismlibrary.com/docs/`
N/A
=> Updated README link to prismlibrary.com documentation

.gitignore, src/Maui/Prism.Maui/Common/MvvmHelpers.cs, src/Prism.Core/Navigation/NavigationResult.cs
This change is the first of a few to enable nullability in Prism.
None.
Added:
None
Changed:
- MvvmHelpers
- NavigationResult
There should be no behavioral changes given nullability is backwards compatible.
=> chore: enable nullability for mvvm helpers

src/Maui/Prism.Maui/PrismAppBuilder.cs
Fixes issue where pressing the back button can cause a double back when the Current Page's parent is a NavigationPage
=> Fix double back on Android

src/Prism.Core/Mvvm/BindableBase.cs, src/Prism.Core/Mvvm/ErrorsContainer.cs, src/Prism.Core/Mvvm/IViewRegistry.cs, src/Prism.Core/Mvvm/PropertySupport.cs, src/Prism.Core/Mvvm/ViewCreationException.cs, src/Prism.Core/Mvvm/ViewModelCreationException.cs, src/Prism.Core/Mvvm/ViewModelLocationProvider.cs, src/Prism.Core/Mvvm/ViewRegistration.cs, src/Prism.Core/Mvvm/ViewRegistryBase{TBaseView}.cs
Enable Nullability for Prism MVVM folder
No Tests added, unless reviewer requests verification of behavior change not previously covered.
- Provide links to bugs here
Changed:
- BindableBase
- ViewRegistry
- ViewRegisration
- ViewModelLocationProvider
- PropertySupport
Should be zero behavior changes because nullability is backwards compatible
=> chore: enable nullability for core mvvm

src/Directory.Build.targets
This Pull Request allows me to build Prism Library and run the Prism Demos on macOS without having to locally comment out packaging concerns
=> chore: build Prism on macOS

src/Maui/Prism.Maui/Common/MvvmHelpers.cs, tests/Maui/Prism.Maui.Tests/Fixtures/Common/MvvmHelperFixture.cs
Fixed a bug that causes the sample application to crash given a `PrismWindow` is somewhere on the navigation stack.
- #3143 
Changed:
- checking `PrismWindow` for the `Page` property on it and passing it to the `GetTarget` method
Ensured the `PrismWindow` gets properly handled and passed the `Page` property on to find the target if available.
=> fix: GetCurrentPage for PrismWindow.Page throwing exception

src/Maui/Prism.Maui/Common/MvvmHelpers.cs
Delays nulling the BindingContext of the View on Android until the View's Unloaded event fires.
- fixes #3113
=> Delay nulling BindingContext on Android

src/Maui/Prism.Maui/Ioc/RegionNavigationRegistrationExtensions.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/LayoutRegionAdapter.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/LayoutViewRegionAdapter.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Regions/RegionFixture.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Views/MockContentRegionPage.cs
Added `LayoutRegionAdapter` to support `Microsoft.Controls.Layout`
#3159
Added:
`public class LayoutRegionAdapter : RegionAdapterBase<Layout>` 
N/a
=> Map LayoutViewRegionAdapter to Maui Layout

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs
=> send android app to background when navigating back on the root page

tests/Maui/Prism.Maui.Tests/Fixtures/Common/MvvmHelperFixture.cs
Enable TabbedPage tests that are disabled due to missing Dispatcher
=> Enable TabbedPage tests

src/Maui/Prism.Maui/Navigation/Regions/Adapters/CarouselViewRegionAdapter.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/CollectionViewRegionAdapter.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/ContentViewRegionAdapter{TContentView}.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/LayoutViewRegionAdapter.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/RegionAdapterBase.cs, src/Maui/Prism.Maui/Navigation/Regions/Adapters/ScrollViewRegionAdapter.cs
=> Refactor to ArgumentNullException.ThrowIfNull

e2e/Maui/MauiModule/ViewModels/ViewModelBase.cs, e2e/Maui/PrismMauiDemo/MauiProgram.cs, src/Maui/Prism.Maui/Controls/PrismNavigationPage.cs, src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, src/Maui/Prism.Maui/Navigation/PrismWindow.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Prism.DryIoc.Maui.Tests.csproj
=> fixing Android hardware button

e2e/Maui/MauiModule/ViewModels/ViewAViewModel.cs, e2e/Maui/MauiModule/ViewModels/ViewModelBase.cs, e2e/Maui/MauiModule/Views/ViewA.xaml, e2e/Maui/PrismMauiDemo/MauiProgram.cs, src/Maui/Prism.Maui/Common/MvvmHelpers.cs, src/Maui/Prism.Maui/Navigation/PrismWindow.cs, src/Maui/Prism.Maui/Navigation/Xaml/NavigationExtensionBase.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, tests/Maui/Prism.Maui.Tests/Fixtures/Navigation/Xaml/GoBackExtensionFixture.cs, tests/Maui/Prism.Maui.Tests/Fixtures/Navigation/Xaml/NavigateToExtensionFixture.cs
Fixed modal navigation for the most common navigation scenarios.
Fixes #3185
=> fixed modal navigation

PrismLibrary.sln, src/Prism.Core/Navigation/Regions/IRegionBehaviorFactory.cs, src/Prism.Core/Navigation/Regions/IRegionBehaviorFactoryExtensions.cs, src/Prism.Core/Navigation/Regions/RegionBehaviorFactory.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Regions/RegionBehaviorFixture.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Regions/Behaviors/RegionBehaviorAMock.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Regions/Behaviors/RegionBehaviorBMock.cs, tests/Wpf/Prism.Wpf.Tests/Mocks/MockRegionBehaviorB.cs, tests/Wpf/Prism.Wpf.Tests/Regions/RegionBehaviorFactoryFixture.cs
Added API to replace an existing behavior with a custom behavior(this is already possible for region adapters). 
- N/a
Added:
- void IRegionBehaviorFactory.AddOrReplace(string behaviorKey, Type behaviorType)
Existing behaviors can be replaced with custom behaviors.
=> Add 'AddOrReplace' to IRegionBehaviorFactory

.github/workflows/build_core.yml, .github/workflows/build_forms.yml, .github/workflows/build_maui.yml, .github/workflows/build_uno.yml, .github/workflows/build_wpf.yml, .github/workflows/ci.yml, .github/workflows/publish-release.yml, .github/workflows/start-release.yml
=> Add release branches to build

src/Maui/Prism.Maui/Modularity/ModuleCatalog.cs, src/Maui/Prism.Maui/Modularity/ModuleInfo.cs, src/Uno/Prism.Uno/Prism.Uno.WinUI.csproj
Use MAUI version of the Modules code for Uno Platform
=> Use Maui version for Modules

src/Maui/Prism.Maui/Modularity/ModuleCatalog.cs, src/Maui/Prism.Maui/PrismAppBuilder.cs, src/Maui/Prism.Maui/PrismAppBuilderExtensions.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Modularity/ModuleCatalogTests.cs
This updates the registration logic for the Modules to avoid a static registration flag. This now is updated to use TryRegister.
This also updates the ModuleCatalog for MAUI/Uno to use a constructor that takes an `IEnumerable<IModuleInfo>` thus allowing instances of `IModuleInfo` to be registered with the container and later injected into the ModuleCatalog. *NOTE* you still need to call ConfigureModuleCatalog or register the services yourself if you prefer to use DI
- Unit Tests fail on reinitialization due to the static flag still being true.
- default ctor -> (IEnumerable<IModuleInfo>)
IModuleInfo can now be injected with DI into the ModuleCatalog on MAUI and Uno. This was not applied to WPF as we are still shipping Unity Container which does not support this.
=> Modularity Fix

src/Maui/Prism.Maui/Ioc/ContainerProvider.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/IoC/ContainerProviderTests.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ConcreteTypeMock.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Converters/MockValueConverter.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Events/TestActionEvent.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/ViewModels/MockXamlViewViewModel.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Views/MockXamlView.xaml, tests/Maui/Prism.DryIoc.Maui.Tests/Mocks/Views/MockXamlView.xaml.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Prism.DryIoc.Maui.Tests.csproj
Resolves https://github.com/PrismLibrary/Prism/issues/3238 by adding `ContainerProvider<T>` based on the previous implementation in `Prism.Forms`.
N/A
Added:
- `ContainerProvider<T>`
N/A
=> Add ContainerProvider for resolving dependencies in XAML

src/Wpf/Prism.Wpf/Ioc/IContainerRegistryExtensions.cs
While in Xamarin.Forms and .NET MAUI we have always returned the IContainerRegistry from the Dialog and Navigation registration extensions, WPF / Uno extensions have not. This PR aligns the behavior between the platforms so that the IContainerProvider is returned allowing you to chain your registration like:
```cs
containerRegistry.RegisterForNavigation<ViewA, ViewAViewModel>()
.RegisterForNavigation<ViewB, ViewBViewModel>();
```
=> Align registration return type

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs
Reduced the wait time between navigations to only be 150 milliseconds.
None
This change will be hardly noticeable.
=> Avoid waiting more than necessary between navigations

src/Maui/Prism.Maui/Navigation/Builder/ITabbedSegmentBuilder.cs, src/Maui/Prism.Maui/Navigation/Builder/TabbedSegmentBuilder.cs, src/Maui/Prism.Maui/Navigation/KnownNavigationParameters.cs, src/Maui/Prism.Maui/Navigation/PageNavigationService.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/DynamicTabbedPageNavigationFixture.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs, tests/Maui/Prism.Maui.Tests/Fixtures/Navigation/NavigationBuilderFixture.cs, tests/Maui/Prism.Maui.Tests/Fixtures/PageNavigationServiceFixture.cs
Configure `TabbedPage.Title`
#3188
Added:
- ITabbedSegmentBuilder ITabbedSegmentBuilder.Title();
- string KnownNavigationParameters.Title
The `Title` of dynamically created `TabbedPagges` is now configurable through the builder.
=> Configure TabbedPage Title

src/Maui/Prism.Maui/Behaviors/EventToCommandBehavior.cs
Fixed #3063
Although #3063 as reported wasn't a bug, just a very problematic code base, it did  lead me to find an actual bug. When the event args of a control event didn't have any custom properties, it would not invoke the event args converter logic, which is not what we want. So I removed that check to fix it.
=> removed check for empty events args object

src/Maui/Prism.Maui/Navigation/Regions/Navigation/RegionNavigationContentLoader.cs, tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Regions/RegionFixture.cs
Fixes `NullReferenceException` being the navigation exception when navigating to an unregistered region
- #3328
None
None
=> Fix navigating to unregistered region error
