Source/PrismLibrary_Tests.sln
Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Mocks/MockView.cs
Source/Wpf/Prism.IocContainer.Wpf.Tests.Support/Prism.IocContainer.Wpf.Tests.Support.csproj
Source/Wpf/Prism.Unity.Wpf.Tests/Mocks/MockServiceLocator.cs
Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
Source/Wpf/Prism.Unity.Wpf.Tests/UnityRegionNavigationContentLoaderFixture.cs

Merge added github tags in .sln file
Moved MockView and MockServiceLocator to their own files

Removed github head tags, refactored out Mocks

---

Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs

Sorry for the formatting changes in here as well. Xamarin Studio formatted the code on save.

Have NavigationParameters act as a Dictionary

---

Source/Windows10/Prism.Unity.Windows/PrismUnityApplication.cs

Can these services be added to the default registration of the unity container?
ps. this is already based on pull request #79 including IDeviceGestureService

[Win10 UWP] Add more services to unity container configuration

---

Source/Windows10/Prism.Windows/AppModel/FrameNavigationService.cs
Source/Windows10/Prism.Windows/Interfaces/IFrameFacade.cs
Source/Windows10/Prism.Windows/Interfaces/INavigationService.cs
Source/Windows10/Prism.Windows/Mvvm/FrameFacadeAdapter.cs

#26 #67
How about something like this for BackStack support in Prism.Windows navigationService .
This way you can remove the last/first or all pages from the backstack with optional parameters for specific pages. eg pageToken and parameter.

[Win10 UAP] Added BackStack support

---

Source/Wpf/Prism.Ninject.Wpf/Prism.Ninject.Wpf.csproj
Source/Wpf/Prism.Ninject.Wpf/packages.config

I think linking to the stable version is more.. stable

Revert to Ninject stable version 3.2.2

---

CONTRIBUTE.md

As I had to look up what the CLA thing was about on one of my latest
PRs, I thought it was useful to share it for everybody willing to
contribute.
Used CoreCLR's readme as guidance.

Added info on the .NET Foundation CLA

---

Source/PrismLibrary.sln
Source/PrismLibrary_Wpf.sln
Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs

Changed solution files as described in #143.
Also re-enabled failing C#6 code to test build.
Did set up AppVeyor for my branch and after setting environment to "Visual Studio 2015" I got a green build with the code reverted to C#6 (when disabling tests, there was 1 Command test failing).

Change solution file for AppVeyor

---

Samples/README.md

Making clear that samples in this repo are test apps, while complete
samples are placed in separate repo's.

Added a README file to the Samples folder

---

README.md

Reason: https://github.com/PrismLibrary/Prism/issues/80

updated breaking changes list in README.md

---

Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/packages.config
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/packages.config

updated the target for Prism.Forms and Prism.Unity.Forms to include WP 8.1.  I Also updated the Unity reference to use v4

updated target for WP8.1

---

Source/Windows10/Prism.Windows/Validation/BindableValidator.cs
Source/Windows10/Prism.Windows/Validation/IValidatableBindableBase.cs
Source/Windows10/Prism.Windows/Validation/ValidatableBindableBase.cs

Can be used for scenarios like dependent properties (#196)

Enable validating a single property

---

Source/Xamarin/Prism.Forms/Navigation/INavigationPageProvider.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationPageProviderAttribute.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj

Added a new NaigationPageProviderAttribute and INavigationProvder interface to support configuring and wrapping pages during navigation.

Added new navigation page provider

---

Source/Windows10/Prism.Windows/PrismApplication.cs

Override the OnActivated method. OnActivated is the entry point for an application when it is launched via means other normal user interaction. This includes Voice Commands, URI activation, being used as a share target from another app, etc.

Added activation behavior

---

Documentation/Xamarin.Forms/DependencyService.md

Changed ViewModela to ViewModels under *Use the Service* header.

Changed ViewModela to ViewModels

---

Documentation/Xamarin.Forms/3-NavigationService.md

First version for issue #265. Needs some more work and a spelling/language check to be really complete.
Still misses the NavigationPageProviderAttribute documentation

Documenting the Navigation Service

---

Documentation/WPF/01-Introduction.md

To make it more accessble.
@brianlagunas hey, accept this! 👍

Added an alt tag to the image

---

Documentation/Xamarin.Forms/3-NavigationService.md
Samples/Xamarin/HelloWorld/HelloWorld.Ninject/HelloWorld.Ninject.Droid/HelloWorld.Ninject.Droid.csproj
Samples/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Samples/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Common/UriParsingHelperFixture.cs
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms/Common/UriParsingHelper.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj

Added the ability to use either relative or absolute Uri navidation

added uri based navigation

---

Source/Prism/Commands/DelegateCommand.cs
Source/Wpf/Prism.Wpf/Common/CallbackHelper.cs
Source/Wpf/Prism.Wpf/Interactivity/InteractionRequest/InteractionRequest.cs

Convert unneeded async methods into normal ones

---

Source/Xamarin/Prism.Forms.Tests/Common/UriParsingHelperFixture.cs
Source/Xamarin/Prism.Forms/Common/UriParsingHelper.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

improved logic to NavigationService.GoBack to include support for parameters and calling OnNavigatedTo/From on respective pages

Implemented GoBack

---

.editorconfig

Add basic .editorconfig for .NET

---

Samples/Xamarin/HelloWorld/HelloWorld/HelloWorld/Bootstrapper.cs
Source/Xamarin/Prism.Forms.Tests/BootstrapperFixture.cs
Source/Xamarin/Prism.Forms/Bootstrapper.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Ninject.Forms/NinjectBootstrapper.cs
Source/Xamarin/Prism.Unity.Forms/UnityBootstrapper.cs

Improved NavigationService to allow navigating from Bootstrapper to
MainPage.  No longer return a Page instance from CreateMainPage.  Now
you navigate to it just like you normally would.

changed bootstrapper to allow navigating to MainPage

---

Source/Xamarin/Prism.Forms.Tests/Mocks/ViewModels/ContentPageMockViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Mocks/Views/ContentPageMock.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms/Navigation/IConfirmNavigationAsync.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj

INavigationService methods now return tasks. Also added new IConfirmNavigationAsync interface.

converted NavigationServcie to async/await

---

Source/Wpf/Prism.Wpf.Tests/Mocks/MockPresentationRegion.cs
Source/Wpf/Prism.Wpf.Tests/Mocks/MockRegion.cs
Source/Wpf/Prism.Wpf/Regions/Behaviors/RegionActiveAwareBehavior.cs
Source/Wpf/Prism.Wpf/Regions/IRegion.cs
Source/Wpf/Prism.Wpf/Regions/Region.cs

added the ability to remove all views from a region by using the new
RemoveAll method.

added RemoveAll to IRegion

---

Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismProperty.snippet
Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommand.snippet
Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommandGeneric.snippet

shortened the snippets names to be a little easier to use

Prism Template Pack - shortened snippet names

---

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs

if the parent window is minimized, then we want to show the popup center
screen by default.

fixed issue #426

---

Source/Prism/Commands/DelegateCommand.cs
Source/Wpf/Prism.Mef.Wpf.Tests/MefServiceLocatorAdapterFixture.cs

Updated DelegateCommand to change private constructors to protected.
Corrected a test because of localized error messages.

 Inheritance of DelegateCommand async methods. Issue #423 

---

Extensibility/TemplatePack/TemplatePack/TemplatePack.csproj
Extensibility/TemplatePack/TemplatePack/source.extension.vsixmanifest

released new app.config module editor

rev'd to v1.3 for release

---

Source/Wpf/Prism.Autofac.Wpf/Prism.Autofac.Wpf.csproj
Source/Wpf/Prism.Mef.Wpf/Prism.Mef.Wpf.csproj
Source/Wpf/Prism.Ninject.Wpf/Prism.Ninject.Wpf.csproj
Source/Wpf/Prism.StructureMap.Wpf/Prism.StructureMap.Wpf.csproj
Source/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
Source/Wpf/Prism.Wpf/Prism.Wpf.csproj

Removed unused references in csproj files

Removed unused references in csproj files

---

Extensibility/TemplatePack/VsPackages/ConfigModuleEditor/ConfigModuleEditorPane.cs

when the configsections are created, it is now add as the first child in the app.config

Templatepack moved configsections

---

Source/PrismLibrary.sln
Source/PrismLibrary_Wpf.sln
Source/Wpf/Prism.StructureMap.Wpf.Tests/Prism.StructureMap.Wpf.Tests.csproj
Source/Wpf/Prism.StructureMap.Wpf.Tests/packages.config
Source/Wpf/Prism.StructureMap.Wpf/Prism.StructureMap.Wpf.csproj
Source/Wpf/Prism.StructureMap.Wpf/packages.config
Source/nuspecs/CreatePrismNuGetPackages.ps1
Source/nuspecs/Prism.StructureMap.nuspec

Removed signing from Prism.StructureMap.Wpf

---

Source/Wpf/Prism.Mef.Wpf.Tests.Support/Prism.Mef.Wpf.Tests.Support.csproj

Added signing key for MEF support test project

---

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Made a small improvement to the NavigationPage logic to help minimize #541 when navigating to a navigation page inside a master detail

Small improvement to NavigationService

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MyMasterDetailViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewBViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Updated INavigationService.Navigate and GoBack methods to NavigateAsync and GoBackAsync. Updated tests.

[XF] Rename INavigationService.Navigate to NavigateAsync #513

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.WinPhone/HelloWorld.WinPhone.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.WinPhone/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/packages.config
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms.Tests/packages.config
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/packages.config
Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
Source/Xamarin/Prism.Ninject.Forms/packages.config
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/packages.config

Improved logic for automatically determining if a page should be navigated to modally or not.

Inproved navigation logic

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml.cs
Source/Xamarin/Prism.Forms.Tests/Mocks/Views/MasterDetailPageMock.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms/Navigation/IMasterDetailPageOptions.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/Properties/AssemblyInfo.cs
Source/Xamarin/Prism.Ninject.Forms/Properties/AssemblyInfo.cs
Source/Xamarin/Prism.Unity.Forms/Properties/AssemblyInfo.cs
Source/nuspecs/Prism.Forms.nuspec
Source/nuspecs/Prism.Unity.Forms.nuspec
Source/nuspecs/Prism.Unity.nuspec

Added a new interface called IMasterDetailPageOptions that allows the INavigationService to control the MasterDetailPage.IsPresented state after a navigation operation. Fixes #570

Added IMasterDetailOptions

---

Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.UWP/Package.appxmanifest
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.UWP/Properties/AssemblyInfo.cs
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.UWP/UnityApp.UWP.vstemplate
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.UWP/UnityAppTemplate.UWP.csproj
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.WinPhone/Package.appxmanifest
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.WinPhone/Properties/AssemblyInfo.cs
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.WinPhone/UnityApp.WinPhone.vstemplate
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.Windows/Package.appxmanifest
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.Windows/Properties/AssemblyInfo.cs
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.Windows/UnityApp.Windows.vstemplate
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp.Windows/UnityAppTemplate.Windows.csproj

Fixed the XF UWP, Windows, and WinPhone project templates.

Fixed XF project template

---

Source/Xamarin/Prism.Forms.Tests/Mocks/ViewModels/MasterDetailPageMockViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Mocks/Views/MasterDetailPageMock.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs

needed to test the VIewModel scenarios

added more tests for IMasterDetailPageOptions

---

Documentation/Xamarin.Forms/4-PageDialogService.md
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/SomeOtherViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Mocks/PageDialogServiceMock.cs
Source/Xamarin/Prism.Forms.Tests/Services/PageDialogServiceFixture.cs
Source/Xamarin/Prism.Forms/Services/PageDialogService/ActionSheetButton.cs
Source/Xamarin/Prism.Forms/Services/PageDialogService/IActionSheetButton.cs
Source/Xamarin/Prism.Forms/Services/PageDialogService/IPageDialogService.cs
Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs

Updated IPageDialogService Async methods to reflect the Async naming convention chosen for the INavigationService.

[XF] Updated IPageDialogService async methods

---

Source/Windows10/Prism.SimpleInjector.Windows/PrismSimpleInjectorApplication.cs
Source/Windows10/Prism.Windows/PrismApplication.cs

Adding resuming callback

---

Extensibility/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio.userprefs
Extensibility/TemplatePack-XamarinStudio/addin-project.xml

This file is required by MomoDevelop in order to build the Xamarin Studio addin.  'm just not sure if I have it in the right place or not.

added addin-project file

---

Source/nuspecs/CreatePrismNuGetPackages.ps1
Source/nuspecs/Prism.Ninject.Forms.nuspec

Adding Nuspec for Prism.Ninject.Forms. Adding nuspec to be part of NuGetPackage script.

Prism.Ninject.Forms

---

Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

GoBackAsync now provides a boolean result to signify if a go back action
was successful or not

improved GoBackAsync to include bool result

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.WinPhone/HelloWorld.WinPhone.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.WinPhone/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/packages.config
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms.Tests/packages.config
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/packages.config
Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
Source/Xamarin/Prism.Ninject.Forms/packages.config
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/packages.config

upgraded XF and made some minor changes

upgraded XF to 2.3.0.46-pre3

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/MainActivity.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Source/Xamarin/Prism.Forms/IPlatformInitializer.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Source/Xamarin/Prism.Ninject.Forms/IPlatformInitializer.cs
Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs
Source/Xamarin/Prism.Unity.Forms/IPlatformInitializer.cs
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs

Added the ability for the platform projects to register custom types
during the PrismApplication initialization process.

added platform initializer

---

Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs

Fixes DisplayActionSheet on iOS

---

Source/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
Source/Wpf/Prism.Wpf.Tests/Regions/RegionManagerRequestNavigateFixture.cs

RegionManager.RequestNavigate tests

---

Source/Prism/Events/PubSubEvent.cs

virtual PubSubEvent.Subscribe

---

README.md

- Fixes incorrect links for Prism.Autofac.Forms 
- Fixes missing links for Prism.DryIoc.Forms
- Adds dash in WPF & Win 10 UWP columns on Prism.{Container}.Forms rows
- Adds &darr; in Xamarin.Forms column on Prism.{Container} rows where there is a separate package for XF

Fixes to Container Specific chart

---

Source/nuspecs/Prism.DryIoc.Forms.nuspec

Reference correct package for DryIoC

---

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

made methods protected and virtual where possible.

---

Source/Prism/Commands/DelegateCommand.cs

marked FromAsyncHandler as Obsolete

---

Extensibility/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio.userprefs
Extensibility/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio/TemplatePack-XamarinStudio.csproj

This fix have been applied as a posible solution for #789, according to this [answer](http://stackoverflow.com/a/21544263/4312396) on Stack Overflow for a similar problem.

Fix error loading project TemplatePack-XamarinStudio

---

Sandbox/Windows10/HelloWorld/HelloWorld.Unity/Package.appxmanifest
Sandbox/Windows10/HelloWorld/HelloWorld.Unity/ViewModels/MainPageViewModel.cs
Sandbox/Windows10/HelloWorld/HelloWorld.Unity/ViewModels/UserInputPageViewModel.cs
Sandbox/Windows10/HelloWorld/HelloWorld.Unity/project.json
Sandbox/Windows10/HelloWorld/HelloWorld.sln
Source/Windows10/Prism.Windows/PrismApplication.cs

App lifecycle: handling OnResume

---

Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismCarouselPage/PrismCarouselPage.csproj
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismCarouselPage/PrismCarouselPage.vstemplate
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismContentPage/PrismContentPage.csproj
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismContentPage/PrismContentPage.vstemplate
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismMasterDetailPage/PrismMasterDetailPage.csproj
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismMasterDetailPage/PrismMasterDetailPage.vstemplate
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismNavigationPage/PrismNavigationPage.csproj
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismNavigationPage/PrismNavigationPage.vstemplate
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismTabbedPage/PrismTabbedPage.csproj
Extensibility/TemplatePack/ItemTemplates/CSharp/Forms/PrismTabbedPage/PrismTabbedPage.vstemplate
Extensibility/TemplatePack/ItemTemplates/CSharp/PrismViewModel/PrismViewModel.csproj
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/PrismUnityApp.csproj
Extensibility/TemplatePack/ProjectTemplates/CSharp/Forms/PrismUnityApp/UnityApp/Properties/AssemblyInfo.cs
Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommand.snippet
Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommandGeneric.snippet
Extensibility/TemplatePack/TemplatePack/source.extension.vsixmanifest
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards.Design/Prism.VisualStudio.Wizards.Design.csproj
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards.Design/Styles.xaml
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards.Design/XamarinFormsNewProjectDialog.xaml
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards.Design/XamarinFormsNewProjectDialog.xaml.cs
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/CreateViewModelForViewWizard.cs
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/Prism.VisualStudio.Wizards.csproj
Extensibility/TemplatePack/VsWizards/Prism.VisualStudio.Wizards/XamarinFormsProjectWizard.cs

Now when you add a new XF page to your project with the Prism Template Pack, a ViewModel is creted and added to the "ViewModels" folder, and the Page is registered for navigation in the App.xaml.cs automatically.

Auto create ViewModel

---

docs/Xamarin-Forms/1-Getting-Started.md

I sense a removal of `Async` suffixes in the future :smile: but until then...

Fix broken code snippet

---

docs/Xamarin-Forms/1-Getting-Started.md

Also make sure it adheres to naming convention

Make ViewModel name consistent across the page

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/project.json
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyNavigationPage.xaml.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/packages.config
Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj
Source/Xamarin/Prism.Autofac.Forms.Tests/packages.config
Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj
Source/Xamarin/Prism.Autofac.Forms/packages.config
Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
Source/Xamarin/Prism.DryIoc.Forms.Tests/packages.config
Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
Source/Xamarin/Prism.DryIoc.Forms/packages.config
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms.Tests/packages.config
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/packages.config
Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
Source/Xamarin/Prism.Ninject.Forms/packages.config
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/packages.config

Small logic fix with NavigationPage

Navigationservice update

---

Documentation/README.md

fix documentation links

---

Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommand.snippet
Extensibility/TemplatePack/TemplatePack/Snippets/CSharp/Prism/PrismPropertyCommandGeneric.snippet
Extensibility/TemplatePack/TemplatePack/source.extension.vsixmanifest

Fix DelegateCommand snippet

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj.bak
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
Source/Xamarin/Prism.Forms/AppModel/IApplicationLifecycle.cs
Source/Xamarin/Prism.Forms/Behaviors/NavigationPageSystemGoBackBehavior.cs
Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Source/Xamarin/Prism.Forms/FormsApplication.cs
Source/Xamarin/Prism.Forms/Navigation/INavigatedAware.cs
Source/Xamarin/Prism.Forms/Navigation/INavigatingAware.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationAware.cs
Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationMode.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationParametersExtensions.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/PrismApplicationBase.cs

There is a new GetNavigationMode extension method off of NavigatonParameters which you can use to get access to the parameter value. This addresses #851

added NavigationMode to NavigationParameters

---

Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs

Autoresolve types with Autofac

---

docs/Xamarin-Forms/1-Getting-Started.md

I saw that the documentation for running the app on iOS wasn't available :)
First PR, so if I make mistakes, please let me know!

Updating documentation for running app on iOS

---

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

moved CanNavigateAsync method into PageUtilities

---

docs/Xamarin-Forms/6-EventToCommandBehavior.md

fix code : docs/Xamarin-Forms/6-EventToCommandBehavior.md

fix docs/Xamarin-Forms/6-EventToCommandBehavior.md

---

Source/Wpf/Prism.Wpf/Modularity/ModuleManager.cs

Enhancement discussed here #916

Making ModuleManager.LoadModulesThatAreReadyForLoad() virtual

---

Source/Xamarin/Prism.Forms.Tests/Navigation/NavigationParametersFixture.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs

Also added new GetValue and GetValues methods

Add support for parameter arrays

---

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs

Bugfix for #959 
Misprint corrected.
Of course, unit tests might be provided.  However, efforts would be better spent for new implementation of interactivity.

Bugfix for WindowContentType

---

Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Updates the NavigationService Push/Pop methods for extensibility for custom purposes like PopupPages.

Make Push/Pop virtual for extensibility

---

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs

Fixed GoBack when in NavigationPage

---

Source/Xamarin/Prism.Forms.Tests/Behaviors/EventToCommandBehaviorFixture.cs
Source/Xamarin/Prism.Forms/Behaviors/EventToCommandBehavior.cs

Fixes issue #978 .
- Update to Element for Generic parameter of EventToCommandBehavior.
- Add confirmation of command execution result.

[XF]Apply EventToCommandBehavior to Element（Page and Cell）

---

Source/Xamarin/Prism.Forms.Tests/Navigation/NavigationParametersFixture.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs

- Added TryGetValue for better compatibility with viewModelState from Prism.Windows

NavigationParameters.TryGetValue

---

Source/Xamarin/Prism.DryIoc.Forms/DryIocExtensions.cs
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs

This was tested locally. This means this should work for the first time...

Fixes DryIoc ViewModelLocator 

---

Source/Wpf/Prism.Mef.Wpf/Modularity/MefFileModuleTypeLoader.Desktop.cs

Use Uri to find local file path from ModuleInfo.Ref

---

docs/Xamarin-Forms/6-EventToCommandBehavior.md

Added quotes

---

Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj
Source/Xamarin/Prism.Autofac.Forms.Tests/packages.config
Source/Xamarin/Prism.Autofac.Forms/AutofacExtensions.cs
Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj
Source/Xamarin/Prism.Autofac.Forms/packages.config
Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
Source/Xamarin/Prism.DryIoc.Forms.Tests/packages.config
Source/Xamarin/Prism.DryIoc.Forms/DryIocExtensions.cs
Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
Source/Xamarin/Prism.DryIoc.Forms/packages.config
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms.Tests/packages.config
Source/Xamarin/Prism.Forms/AppModel/RuntimePlatform.cs
Source/Xamarin/Prism.Forms/Platform{T}.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/Services/DeviceService.cs
Source/Xamarin/Prism.Forms/Services/IDeviceService.cs
Source/Xamarin/Prism.Forms/Services/RuntimePlatform.cs
Source/Xamarin/Prism.Forms/packages.config
Source/Xamarin/Prism.Ninject.Forms/NinjectExtensions.cs
Source/Xamarin/Prism.Ninject.Forms/Prism.Ninject.Forms.csproj
Source/Xamarin/Prism.Ninject.Forms/packages.config
Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Source/Xamarin/Prism.Unity.Forms.Tests/packages.config
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/UnityExtensions.cs
Source/Xamarin/Prism.Unity.Forms/packages.config

Implemented new updates to the IDeviceService and the RegisterTypeForNavigationOnPlatform extension methods to deal with the newly deprecated OnPlatform API's made by Xamarin.

Onplatform updates

---

Source/Windows10/Prism.Autofac.Windows/project.json
Source/Wpf/Prism.Autofac.Wpf.Tests/Prism.Autofac.Wpf.Tests.csproj
Source/Wpf/Prism.Autofac.Wpf.Tests/packages.config
Source/Wpf/Prism.Autofac.Wpf/Prism.Autofac.Wpf.csproj
Source/Wpf/Prism.Autofac.Wpf/packages.config
Source/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
Source/Wpf/Prism.DryIoc.Wpf.Tests/packages.config
Source/Wpf/Prism.DryIoc.Wpf/DryIocBootstrapper.cs
Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
Source/Wpf/Prism.DryIoc.Wpf/packages.config
Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj
Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs

Updates Autofac & DryIoc
Updates deprecated RegisterInstance to UseInstance for DryIoc

Container Updates

---

Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs
Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs

Reverts PrismLibrary/Prism#1073

Revert "make it easier to access the container"

---

.github/CONTRIBUTING.md
docs/Assembly-Versioning.md
docs/Download-and-Setup-Prism.md
docs/NuGet-Packages.md
docs/WPF/01-Introduction.md
docs/WPF/02-Initializing.md
docs/WPF/03-Managing-Dependencies.md
docs/WPF/04-Modules.md
docs/WPF/05-Implementing-MVVM.md
docs/WPF/06-Advanced-MVVM.md
docs/WPF/07-Composing-the-UI.md
docs/WPF/08-Navigation.md
docs/WPF/09-Communication.md
docs/WPF/10-Deploying.md
docs/WPF/Appendix-A-Glossary.md
docs/WPF/Appendix-B-Patterns.md
docs/WPF/Appendix-C-Prism-Library.md
docs/WPF/Appendix-D-Extending-Prism.md
docs/WPF/Appendix-E-Click-Once.md
docs/Xamarin-Forms/1-Getting-Started.md
docs/Xamarin-Forms/2-ViewModelLocator.md
docs/Xamarin-Forms/3-Navigation-Service.md
docs/Xamarin-Forms/4-Page-Dialog-Service.md
docs/Xamarin-Forms/5-Dependency-Service.md
docs/Xamarin-Forms/6-EventToCommandBehavior.md

Fixing improper Markdown formatting across docs.

Fix doc formatting

---

docs/Download-and-Setup-Prism.md
docs/WPF/03-Managing-Dependencies.md
docs/WPF/04-Modules.md
docs/WPF/05-Implementing-MVVM.md
docs/WPF/06-Advanced-MVVM.md
docs/WPF/07-Composing-the-UI.md
docs/WPF/Appendix-D-Extending-Prism.md
docs/WPF/Appendix-E-Click-Once.md
docs/Xamarin-Forms/1-Getting-Started.md
docs/Xamarin-Forms/4-Page-Dialog-Service.md
docs/Xamarin-Forms/5-Dependency-Service.md
docs/Xamarin-Forms/6-EventToCommandBehavior.md
docs/Xamarin-Forms/7-Working-With-TabbedPages.md

fixes issues with sublists as pointed out by @bartlannoeye 
adds docs for working with XF TabbedPage's

Fix sublists

---

README.md

- fixes some formatting issues
- adds info for MyGet feed
- preps docs for Prism 7 with platforms in separate packages

adding myget info

---

README.md

UWP and WPF share the same package

Removed .Windows from UWP IoC packages

---

Source/Xamarin/Prism.Forms/Modularity/IModuleCatalog.cs
Source/Xamarin/Prism.Forms/Modularity/IModuleCatalogExtensions.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleCatalog.cs

Module extensions

---

Source/Xamarin/Prism.Forms/Modularity/IModuleCatalogExtensions.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleCatalog.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleManager.cs

improvements to modules API

---

Source/Wpf/Prism.Autofac.Wpf/AutofacBootstrapper.cs
Source/Wpf/Prism.Autofac.Wpf/Prism.Autofac.Wpf.csproj
Source/Wpf/Prism.Autofac.Wpf/Regions/AutofacRegionNavigationContentLoader.cs

added the AutofacRegionNavigationContentLoader

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyNavigationPage.xaml.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewA.xaml.cs
Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewB.xaml.cs
Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewC.xaml.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

fixed the navigation logic when navigating within NavigationPages

Fixed #1166

---

Source/Directory.Build.props

fixes issue where IS_PREVIEW is undefined

fix build issue

---

README.md

update MyGet links

---

Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs

made CreateDefaultWindow virtual

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/INavigationServiceExtensionsFixture.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs

added support for IConfirmNavigationAsync and INavigationAware interfaces. Also added error handling to provide better exception messages than what XF gives you.

improved PopToRootAsync with I-Aware methods

---

Source/Prism.Tests/Commands/DelegateCommandFixture.cs
Source/Prism.Tests/Events/EventBaseFixture.cs
Source/Prism.Tests/Mvvm/ErrorsContainerFixture.cs

Fix some xUnit warnings

---

Source/Wpf/Prism.Wpf/Mvvm/ViewModelLocator.cs

Check for design mode in ViewModelLocator

---

Source/Wpf/Prism.Wpf.Tests/BootstrapperFixture.cs
Source/Wpf/Prism.Wpf/Bootstrapper.cs

Bootstrapper.OnInitialized added.

---

Source/Wpf/Prism.Wpf/Modularity/AssemblyResolver.Desktop.cs

provide file path in exception

---

Source/Xamarin/Prism.Autofac.Forms/Navigation/AutofacPageNavigationService.cs
Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs
Source/Xamarin/Prism.DryIoc.Forms/Navigation/DryIocPageNavigationService.cs
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
Source/Xamarin/Prism.Forms.Tests/Mocks/PageNavigationServiceMock.cs
Source/Xamarin/Prism.Forms/Behaviors/IPageBehaviorFactory.cs
Source/Xamarin/Prism.Forms/Behaviors/PageBehaviorFactory.cs
Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs
Source/Xamarin/Prism.Ninject.Forms/Navigation/NinjectPageNavigationService.cs
Source/Xamarin/Prism.Ninject.Forms/PrismApplication.cs
Source/Xamarin/Prism.Unity.Forms/Navigation/UnityPageNavigationService.cs
Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs

Added PageBehaviorFactory

---

Source/Directory.Build.props
Source/Directory.build.targets
Source/build/Prism.Autofac.Wpf.nuspec
Source/build/Prism.DryIoc.Wpf.nuspec
Source/build/Prism.Mef.Wpf.nuspec
Source/build/Prism.Ninject.Wpf.nuspec
Source/build/Prism.StructureMap.Wpf.nuspec
Source/build/Prism.Unity.Wpf.nuspec
Source/build/Prism.Wpf.nuspec

Enables the disabling of a publish by platform
Fixes issue where Copy task fails to copy non-existent xml docs in debug

General fixes

---

Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

navigate async if parent is tabbed or carousel page

---

Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs

Optimize Xamarin Forms DryIoc

---

Source/Wpf/Prism.Wpf.Tests/Regions/RegionNavigationJournalFixture.cs
Source/Wpf/Prism.Wpf.Tests/Regions/RegionNavigationServiceFixture.new.cs
Source/Wpf/Prism.Wpf/Prism.Wpf.csproj
Source/Wpf/Prism.Wpf/Regions/IJournalAware.cs
Source/Wpf/Prism.Wpf/Regions/IRegionNavigationJournal.cs
Source/Wpf/Prism.Wpf/Regions/RegionNavigationJournal.cs
Source/Wpf/Prism.Wpf/Regions/RegionNavigationService.cs

Persist in history

---

Source/Directory.Build.props
Source/build/nuget.ps1

updates the package release notes for CI and releases

update package release notes

---

Source/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
Source/Wpf/Prism.Wpf.Tests/Regions/NavigationParametersFixture.cs
Source/Wpf/Prism.Wpf/Regions/NavigationParameters.cs

added extension methods to NavgationParameters

---

Source/Wpf/Prism.Wpf.Tests/ListDictionaryFixture.cs
Source/Wpf/Prism.Wpf/Common/ListDictionary.cs

renamed ambiguous methods

---

Source/Windows10/Prism.Unity.Windows/Prism.Unity.Windows.csproj
Source/Wpf/Prism.StructureMap.Wpf.Tests/Prism.StructureMap.Wpf.Tests.csproj
Source/Wpf/Prism.StructureMap.Wpf.Tests/packages.config
Source/Wpf/Prism.StructureMap.Wpf/Prism.StructureMap.Wpf.csproj
Source/Wpf/Prism.StructureMap.Wpf/packages.config
Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
Source/Wpf/Prism.Unity.Wpf.Tests/UnityBootstrapperRunMethodFixture.cs
Source/Wpf/Prism.Unity.Wpf.Tests/packages.config
Source/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
Source/Wpf/Prism.Unity.Wpf/packages.config
Source/Xamarin/Prism.DI.Forms.Tests/MockForms.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj

updated to the latest version of Unity, and to 2.5 of Xamarin.Forms and fixed all the everything that they broke.

Xamarin upgrade

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/MainActivity.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Properties/AndroidManifest.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/Resource.Designer.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/layout/Tabbar.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/layout/toolbar.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/values-v21/styles.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/values/colors.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/Resources/values/styles.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/project.json
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/packages.config
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/packages.config
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/Views/MyTabbedPage.xaml
Sandbox/Xamarin/HelloWorld/ModuleA/packages.config
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
Source/Xamarin/Prism.Forms/Navigation/INavigateInternal.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationService.cs
Source/Xamarin/Prism.Forms/Navigation/INavigationServiceExtensions.cs
Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Fixes #946 
You can now break out into a modal nav during a deep link.
```
NavigatAsync("NavigationPage/ViewA/ViewB/NavigationPage?useModalNavigation=true/ViewC/ViewD");
```

Support useModalNavigation for specific segments in deep linking

---

Source/Xamarin/Prism.Autofac.Forms.Tests/Mocks/PrismApplicationMock.cs
Source/Xamarin/Prism.DryIoc.Forms.Tests/Mocks/PrismApplicationMock.cs
Source/Xamarin/Prism.Forms/Modularity/IModuleCatalog.cs
Source/Xamarin/Prism.Forms/Modularity/IModuleCatalogExtensions.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleCatalog.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleInfo.cs
Source/Xamarin/Prism.Forms/Modularity/ModuleManager.cs
Source/Xamarin/Prism.Unity.Forms.Tests/Mocks/PrismApplicationMock.cs

fixed ModuleInfo ctors

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Droid/HelloWorld.Droid.csproj.bak
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Added the ability to select tabs when navigating from a MasterDetailPage and reusing the TabbedPage.  This was behavior was unintentionally broken with the 7.0 release.
- #1333 
In 6.3 selecting a tab when navigating from a MasterDetailPage would have been as follows:
```
NavigationPage/MyTabbedPage/TabPageA
NavigationPage/MyTabbedPage/TabPageB
NavigationPage/MyTabbedPage/TabPageC
```
Now you can do this:
```
NavigationPage/MyTabbedPage?selectedTab=TabPageA
NavigationPage/MyTabbedPage?selectedTab=TabPageB
NavigationPage/MyTabbedPage?selectedTab=TabPageC
```

Implemented TabbedPage selected tab when in MDP

---

Source/Wpf/Prism.Wpf/Interactivity/InteractionRequest/Notification.cs

Reverts PrismLibrary/Prism#1341
This was a bad approach to fix a non-existent problem.

Revert "Notification now implements INotifyPropertyChanged"

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MyMasterDetailViewModel.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MyNavigationPageViewModel.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/SomeOtherViewModel.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/ViewModelBase.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleAModule.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/MyTabbedPageViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewBViewModel.cs
Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewCViewModel.cs
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

When reusing a NavigationPage in a MasterDetailPage scenario, OnNavigatedFrom is now called.
- #1353

OnNavigatedFrom now called properly when reusing NavigationPage

---

Source/Prism/Navigation/INavigatedAwareAsync.cs
Source/Prism/Navigation/NavigationMode.cs

Added one new file: `INavigatedAwareAsync.cs`
1. `Task OnNavigatedToAsync(INavigationParameters parameters);`
Added new enums in: `NavigationMode.cs`
1. `Forward`
2. `Refresh`
These will enable Prism.Windows
// Jerry

Adding files for Prism.Windows

---

Source/Prism/Navigation/INavigatedAwareAsync.cs
Source/Prism/Navigation/NavigationMode.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationMode.cs

Added some API docs to Jerry's PR

API Docs for Jerry's PR

---

Source/Wpf/Prism.Autofac.Wpf/PrismApplication.cs
Source/Wpf/Prism.Wpf/PrismApplicationBase.cs

Fixed Autofac ServiceLocator in PrismApplication

---

Source/Prism/Commands/PropertyObserver.cs

I noticed a typo when faced with a `NotSupportedException` and it _rattled_ me enough to submit a PR to fix it. 
-N/A
None
None
- N/A: Has tests (if omitted, state reason in description), 
- [ X] Rebased on top of master at time of PR
- [ X ] Changes adhere to coding standard

Fixing a typo

---

Source/Wpf/Prism.Wpf.Tests/Regions/NavigationParametersFixture.cs
Source/Wpf/Prism.Wpf/Regions/NavigationParameters.cs
Source/Xamarin/Prism.Forms.Tests/Navigation/NavigationParametersFixture.cs
Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs

Modified the ToString method of NavigationParameters to handle null values.
- #1543

Fixed navigationParameters.ToString with null values

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs

Recreate navigation pages every time when using MasterDetailPage
- #1546 
Transitions on iOS now work properly

MDP Navigation- recreate NavigationPages every time

---

Source/Wpf/Prism.Wpf/Regions/Behaviors/DelayedRegionCreationBehavior.cs

If region is a dependency object, we hold an instance of the DelayedRegionCreationBehavior so that the target region is not collected by the GC.
- #1328

Allow region to attach to DependencyObject

---

Source/Prism.Tests/Mvvm/ErrorsContainerFixture.cs
Source/Prism/Mvvm/ErrorsContainer.cs

Add new method to return all errors in the container
Added : 
Dictionary<string, List<T>> ErrorsContainer.GetAllErrors()

Add new method to return all errors in the container

---

Source/Prism/Mvvm/ViewModelLocationProvider.cs

Fixed minor typing errors in the ViewModelLocationProvider class file.

Corrected the ViewModelLocationProvider's comments

---

Source/Windows10/Prism.DryIoc.Windows/DryIocContainerExtension.cs
Source/Windows10/Prism.Unity.Windows/Prism.Unity.Windows.csproj
Source/Windows10/Prism.Windows/Ioc/ContainerProvider.cs
Source/Windows10/Prism.Windows/Ioc/IContainerRegistryExtensions.cs
Source/Windows10/Prism.Windows/Modularity/IModuleCatalogExtensions.cs
Source/Windows10/Prism.Windows/Modularity/ModuleCatalog.cs
Source/Windows10/Prism.Windows/Modularity/ModuleManager.cs
Source/Windows10/Prism.Windows/Mvvm/ViewModelLocator.cs
Source/Windows10/Prism.Windows/Navigation/INavigationServiceExtensions.cs
Source/Windows10/Prism.Windows/Navigation/IPlatformNavigationService.cs
Source/Windows10/Prism.Windows/Navigation/NavigationEventArgsExtensions.cs
Source/Windows10/Prism.Windows/Navigation/NavigationPath.cs
Source/Windows10/Prism.Windows/Navigation/PathBuilder.cs
Source/Windows10/Prism.Windows/PrismApplicationBase.xaml.cs
Source/Windows10/Prism.Windows/Services/Gesture/GestureService.cs
Source/Windows10/Prism.Windows/Services/Gesture/IGestureService.cs
Source/Windows10/Prism.Windows/Utilities/XamlUtilities.cs

Quick code cleanup, no functional changes

Quick cleanup of UWP libraries before adding tests

---

Source/Windows10/Prism.Windows/PrismApplicationBase.core.cs

added the missing registration for the IContainerExtension.
- #1638

registered the container extension

---

Source/Directory.Build.props
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
Source/build/azure-pipelines.core.yml
Source/build/azure-pipelines.uwp.yml
Source/build/azure-pipelines.wpf.yml
Source/build/azure-pipelines.xf.yml
Source/build/azure-pipelines.yml
Source/global.json

Adds XmlnsDefinition to DryIoc & Unity packages for Xamarin Forms
Updates build definitions

Build & XF Update

---

Source/build/steps/build.yml

Changes build to use public preview for Core 3

use public preview for .NET Core 3

---

Source/Prism.Tests/Events/PubSubEventFixture.cs
Source/Prism/Events/EventBase.cs

Reverted the EventBase class to it's previous implementation due to the major perf issue introduced.
- #1505 
Added:
- void Prune();

Reverted EventBase

---

Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PrismApplicationFixture.cs
Source/Xamarin/Prism.DI.Forms.Tests/MockForms.cs
Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationMockPlatformAware.cs
Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/AutowireViewTablet.cs
Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/ViewAMockAndroid.cs
Source/Xamarin/Prism.Forms/Ioc/IContainerRegistryExtensions.cs

Fixes bug with Platform specific View Registration
- Fixes #1700 OnPlatform View registration
n/a
n/a

Platform specific view registration

---

Source/Windows10/Prism.Unity.Windows/PrismIocExtensions.cs
Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms/Navigation/Xaml/GoBackExtension.cs
Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigateToExtension.cs
Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj

Updates Xamarin Forms.
Makes Navigation Extensions Bindable
n/a
n /a
NavigationExtensionBase now inherits from BindableBase and properties are now BindableProperties

Forms updates

---

Source/Prism/Prism.csproj
Source/Wpf/Prism.Wpf.Tests/BootstrapperFixture.cs
Source/Wpf/Prism.Wpf/Bootstrapper.cs
Source/Wpf/Prism.Wpf/PrismApplicationBase.cs
Source/Wpf/Prism.Wpf/Regions/Behaviors/IDestructibleRegionBehavior.cs

Adds support for IDestructible
- #1296 
Added:
- IDestructibleRegionBehavior
- IDestructible
No behavior changes

[WPF] Added support for IDestructible

---

Source/Wpf/Prism.Wpf/Services/Dialogs/DefaultDialogs/DialogWindow.xaml
Source/Wpf/Prism.Wpf/Services/Dialogs/DialogViewModelBase.cs
Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogAware.cs

Removed IconSource property from IDialogAware

removed IconSource property

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/Properties/AndroidManifest.xml
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/Resources/Resource.designer.cs
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
Source/Prism/Prism.csproj
Source/Windows10/Prism.DryIoc.Windows/Prism.DryIoc.Windows.csproj
Source/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs

General Maintenance... 
- Performing update to Xamarin Forms 3.6 due to some potential incompatibilities that have been noticed. 
- Updating DryIoc to 4.0. 
- Migrating the Android DependencyResolver logic from the Container's PrismApplication to PrismApplicationBase
Moved Android specific build target from the Container level to Platform level package thanks to the recent updates to the IOC abstractions

Updates for Forms & DryIoc

---

Source/Prism/Prism.csproj
Source/Xamarin/Prism.Forms/Prism.Forms.csproj

These conditions can't be met anymore, so no need for them to stay in the codebase.

Cleanup project files

---

Source/Prism/Commands/DelegateCommandBase.cs
Source/Prism/Ioc/IContainerExtension.cs
Source/Prism/Ioc/IContainerProvider.cs
Source/Prism/Modularity/IModule.cs
Source/Prism/Modularity/IModuleInfoGroup.cs
Source/Prism/Modularity/ModuleCatalogBase.cs
Source/Prism/Mvvm/ErrorsContainer.cs

Small documentation fixes, removed unused usings
- No bugs fixed, besides typos.
None, just documentation.
No changes in behavior.

Documentation fixes

---

Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs

Adds support for using the Dialog Service with Shell
- fixes #1865
none
Adds internal check for when the MainPage is set to a Shell

Support Shell for Dialogs

---

Source/Prism.Tests/Events/DelegateReferenceFixture.cs
Source/Prism.Tests/Prism.Tests.csproj
Source/Prism/Prism.csproj
Source/PrismLibrary.sln
Source/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
Source/Wpf/Prism.Ninject.Wpf.Tests/Prism.Ninject.Wpf.Tests.csproj
Source/Wpf/Prism.Ninject.Wpf/Prism.Ninject.Wpf.csproj
Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
Source/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
Source/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
Source/Wpf/Prism.Wpf/Prism.Wpf.csproj
Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
Source/build/steps/prepare-build.yml
Source/build/steps/set-runtime.yml
Source/global.json

Updates various packages including SDK Extras to fix build issues for Xamarin.Forms
- fixes #1926 
none
none

Build Updates

---

Source/Xamarin/Prism.Forms/PrismApplicationBase.cs

Fixes NRE when app put to sleep when MainPage isn't set
#1708 
None
None

Fixes NRE when app put to sleep when MainPage isn't set

---

Sandbox/Wpf/HelloWorld/HelloWorld/App.xaml.cs
Sandbox/Wpf/HelloWorld/HelloWorld/HelloWorld.csproj
Sandbox/Wpf/HelloWorld/HelloWorld/ViewModels/MainWindowViewModel.cs
Sandbox/Wpf/HelloWorld/HelloWorld/Views/MainWindow.xaml
Sandbox/Wpf/HelloWorld/HelloWorld/Views/ViewA.xaml
Sandbox/Wpf/HelloWorld/HelloWorld/Views/ViewA.xaml.cs
Source/Wpf/Prism.DryIoc.Wpf/PrismApplication.cs
Source/Wpf/Prism.DryIoc.Wpf/Regions/DryIocRegionNavigationContentLoader.cs

Added a content loader for Dry IoC so that custom named views will work properly during region navigation
INavigationAware.IsNavigationTarget now respects custom named views during region navigation.

Added content loader for DryIoC

---

Source/Xamarin/Prism.Forms/Navigation/NavigationMode.cs

Simply fixes some spelling mistakes in the NavigationMode xml comments.
None
None
Omitted due to spelling mistake fix.

fix: Spelling mistakes in NavigationMode comments

---

Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/Properties/AndroidManifest.xml
Source/Directory.Build.props
Source/build/azure-pipelines.yml
Source/build/jobs/sandbox-android.yml
Source/build/jobs/sandbox-ios.yml
Source/build/jobs/sandbox-wpf.yml
Source/build/steps/prepare-build.yml

turning on Sandbox builds for Xamarin projects

enabling Xamarin Sandbox builds

---

Source/Wpf/Prism.Wpf/Services/Dialogs/DialogService.cs

Made methods in the `DialogService.cs` class virtual so they can be customized per the developer requirements
- #1982 
Changed:
- protected virtual IDialogWindow CreateDialogWindow
- protected virtual void ConfigureDialogWindowContent
- protected virtual void ConfigureDialogWindowEvents
- protected virtual void ConfigureDialogWindowProperties
None

DialogService.cs methods made virtual

---

build/jobs/prism-core.yml
build/jobs/prism-forms.yml
build/jobs/prism-wpf.yml
build/steps/publish-vstest-results.yml
build/steps/test-core.yml
build/steps/test-forms.yml
build/steps/test-wpf.yml

I figured I'd make it publish test results as early in the pipelines as possible.
- #2080 
None
None

Fix test run publishing

---

src/Uno/Prism.Uno/Prism.Uno.csproj
src/Uno/Prism.Uno/PrismApplicationBase.cs

- Fixes the missing resources in the uap10.0 target for Windows
- Removes the unused CommonServiceLocator dependency for uap10.0
- fixes #2093 
~~- [ ] Has tests (if omitted, state reason in description)~~

Fix Windows library resources

---

tests/Wpf/Prism.Wpf.Tests/PrismApplicationBaseFixture.cs

Added tests for PrismApplicationBase. I also modified the PrismBootstrapperBase to use class fixtures to share setup data

Added tests for PrismApplicationBase

---

src/Forms/Prism.Forms/Xaml/ParameterExtension.cs
src/Prism.Core/Common/ParametersBase.cs
src/Prism.Core/Common/ParametersExtensions.cs
src/Prism.Core/Mvvm/ErrorsContainer.cs
src/Prism.Core/Navigation/IDestructible.cs
src/Wpf/Prism.Wpf/Regions/IRegionNavigationJournal.cs

Updated XML Documenation for the following files:
Prism.Forms
ParameterExtension.cs
Prism.Core
ParameterBase.cs
ParametersExtensions.cs
ErrorsContainer.cs
IDestructible.cs
Prism.Wpf
IRegionNavigationJournal.cs
None
None
None

Updated some more XML comments

---

src/Forms/Prism.Forms/AppModel/ApplicationStore.cs
src/Forms/Prism.Forms/AppModel/IApplicationLifecycleAware.cs
src/Forms/Prism.Forms/AppModel/IApplicationStore.cs
src/Forms/Prism.Forms/AppModel/RuntimePlatform.cs
src/Forms/Prism.Forms/Behaviors/EventToCommandBehavior.cs

ApplicationStore.cs
EventToCommandBehavior.cs
IApplicationLifecycleAware.cs
IApplicationStore.cs
RuntimePlatform.cs
Describe your changes here.
None
None
Added:
None
Changed:
None
None
No test needed

Added documenation for 5 cs files

---

README.md

Housekeeping work. Fixes link to Prism.Uno Nuget package.
[#2130](https://github.com/PrismLibrary/Prism/issues/2130)
None
None

Fix link to Uno Nuget package

---

src/Prism.Core/Common/ParametersBase.cs
src/Wpf/Prism.Wpf/Services/Dialogs/DialogParameters.cs
src/Wpf/Prism.Wpf/Services/Dialogs/IDialogParameters.cs

Fixed some spelling mistakes on ParametersBase comments.
Added periods
Added XML comments to Prism.WPF IDialogParameters
N/A
N/A
N/A

XML comments to Prism.WPF IDialogParameters

---

e2e/Uno/HelloUnoWorld.Droid/HelloUnoWorld.Droid.csproj
e2e/Uno/HelloUnoWorld.UITests/HelloUnoWorld.UITests.csproj
e2e/Uno/HelloUnoWorld.UWP/HelloUnoWorld.UWP.csproj
e2e/Uno/HelloUnoWorld.Wasm/HelloUnoWorld.Wasm.csproj
e2e/Uno/HelloUnoWorld.iOS/HelloUnoWorld.iOS.csproj
e2e/Uno/ModuleA/ModuleA.csproj
src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.csproj
src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.csproj
src/Uno/Prism.Uno/Prism.Uno.csproj

Update to Uno 3.0

---

src/Forms/Prism.Forms/Prism.Forms.csproj
src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.csproj
src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.csproj
src/Uno/Prism.Uno/Prism.Uno.csproj
src/Wpf/Prism.Wpf/Prism.Wpf.csproj

Updates the base description for all Prism Platform packages. Adds descriptions and tags for Uno packages
fixes #2159
n/a
n/a
n/a

update package descriptions

---

src/Forms/Prism.Forms/Services/Dialogs/DialogPage.cs
src/Forms/Prism.Forms/Services/Dialogs/DialogService.cs

Fixes known issue from PR #2169. Work around to fix regression with iOS Modal Transparency.
- Modal Transparency with Dialogs
none
none

Fix iOS modal transparency

---

README.md

Just added missing ".com" in URLs

Fixed Twitter URLs.

---

.editorconfig
build/jobs/uno-uitest.yml
build/scripts/xcode-update.sh
build/steps/set-runtime.yml

Provides build update so that we can control the version of Xcode when needed from the Build Variables set in Azure Pipelines
- Broken Builds

provide xcode override method

---

src/Wpf/Prism.Wpf/Regions/RegionNavigationContentLoader.cs

Added new AddViewToRegion method to RegionNavigatinContentLoader
- #2294

Added new AddViewToRegion method

---

build/steps/prepare-build.yml
build/steps/set-runtime.yml
e2e/Forms/src/HelloWorld.Android/HelloWorld.Android.csproj
e2e/Forms/src/HelloWorld.Android/Properties/AndroidManifest.xml
e2e/Forms/src/HelloWorld.Android/Resources/layout/Tabbar.xml
e2e/Forms/src/HelloWorld.Android/Resources/layout/Toolbar.xml
e2e/Forms/src/HelloWorld.Android/SplashActivity.cs
e2e/Uno/HelloUnoWorld.Droid/HelloUnoWorld.Droid.csproj
e2e/Uno/HelloUnoWorld.Droid/Properties/AndroidManifest.xml
e2e/Uno/ModuleA/ModuleA.csproj
global.json
src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.csproj
src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.csproj
src/Uno/Prism.Uno/Prism.Uno.csproj

Fixes build issue caused by updated Uno Package targeting AndroidX
n/a
n/a
n/a

fixing Uno build

---

e2e/Forms/src/HelloWorld.Android/HelloWorld.Android.csproj
e2e/Forms/src/HelloWorld/App.xaml.cs
e2e/Forms/src/ModuleA/ViewModels/ViewAViewModel.cs
src/Forms/Prism.Forms/Navigation/Xaml/Navigation.cs
tests/Forms/Prism.DI.Forms.Tests/Fixtures/Navigation/NavigationServiceFixture.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/PrismApplicationMock.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlMasterDetailViewMockViewModel.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlTabbedViewMockViewModel.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlViewMockAViewModel.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/XamlMasterDetailViewMock.xaml
tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/XamlMasterDetailViewMock.xaml.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/XamlTabbedViewMock.xaml
tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/XamlTabbedViewMock.xaml.cs
tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMockA.xaml
tests/Forms/Prism.DI.Forms.Tests/Prism.DI.Forms.Tests.projitems

This fixes the issues reported where the NavigationService would be resolved with the wrong Page context breaking navigation.
- closes 2218
n/a
n/a

Fixing DI NavigationService resolution

---

Packages.props
build/azure-pipelines.yml
global.json
version.json

Bumps to 8.2-pre
Updates dependencies
Disables consistently failing e2e stage
none
none
none

Bump Prism version to 8.2 preview

---

Directory.Build.targets
Packages.props
e2e/Uno/HelloUnoWorld.Shared/App.xaml.cs
e2e/Uno/HelloWorld.sln
e2e/Uno/ModuleA/ModuleA.WinUI.csproj
e2e/Uno/WinUI/HelloUnoWorld.Windows.Desktop/HelloUnoWorld.Windows.Desktop.csproj
e2e/Uno/WinUI/HelloUnoWorld.Windows.Package/HelloUnoWorld.Windows.Package.wapproj
global.json
src/Uno/Prism.Uno/Extensions/DependencyObjectExtensions.Uno.cs

Updates WinUI support to WinAppSDK 1.0 and Uno 4.0.
None.
None.
None.

chore: Update to Uno 4.0 and WinAppSDK 1.0

---

e2e/Uno/HelloUnoWorld.Shared/App.xaml.cs

Fixes Uno Skia WPF e2e sample build
None
None
None.

fix: Invalid Uno Skia e2e template change

---

.github/CONTRIBUTING.md
LICENSE
README.md

Removed references to .NET Foundation
- #2683

Removed references to .NET Foundation

---

Packages.props

Bumps our core & test dependencies. DryIoc will be updated later as we look at bringing over changes in from Prism.Maui.

bump dependencies

---

src/Forms/Prism.Forms/Navigation/TabbedPages/INavigationServiceExtensions.cs
tests/Forms/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs

In some of our projects we needed to navigate to tabs from the main `TitleView` so we changed a little bit of the `TabbedPage` code. 
Hope it'll be useful for you guys and users too. ❤️

Ability to select tabs from TabbedPage's TitleView

---

src/Directory.Build.targets
src/winappsdk-workaround.targets

Adding WinAppSdk workaround targets

add winappsdk workaround targets

---

.github/workflows/ci.yml

Fix for the CI consolidation task

ci: fix consolidation task

---

Directory.Packages.props

Update nuget packages

---

src/Prism.Core/Prism.Core.csproj
src/Prism.Core/Properties/IsExternalInit.cs
src/Prism.Events/Prism.Events.csproj
src/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
src/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
src/Wpf/Prism.Wpf/Prism.Wpf.csproj

Revert changes - .NET 461 support

---

Directory.Build.targets
src/Uno/Prism.Uno/PrismApplicationBase.cs
winappsdk-workarounds.targets

Adding WinAppSdk Workaround targets to resolve pri issue

fix: winappsdk pri duplication

---

Directory.Packages.props
e2e/Uno/HelloWorld.Mobile/HelloWorld.Mobile.csproj
e2e/Uno/HelloWorld.Skia.Gtk/HelloWorld.Skia.Gtk.csproj
e2e/Uno/HelloWorld.Skia.Linux.FrameBuffer/HelloWorld.Skia.Linux.FrameBuffer.csproj
e2e/Uno/HelloWorld.Skia.WPF/HelloWorld.Skia.WPF.csproj
e2e/Uno/HelloWorld.Wasm/HelloWorld.Wasm.csproj
e2e/Uno/HelloWorld.Windows/HelloWorld.Windows.csproj
e2e/Uno/HelloWorld/HelloWorld.csproj

Updates Prism.Uno.WinUI to Uno 5.0\

Update to Uno 5.0

---

e2e/Uno/Directory.Build.props
e2e/Uno/HelloWorld.Base/HelloWorld.Base.csproj
e2e/Uno/HelloWorld.Mobile/HelloWorld.Mobile.csproj
e2e/Uno/HelloWorld.Skia.Gtk/HelloWorld.Skia.Gtk.csproj
e2e/Uno/HelloWorld.Skia.Linux.FrameBuffer/HelloWorld.Skia.Linux.FrameBuffer.csproj
e2e/Uno/HelloWorld.Skia.WPF/HelloWorld.Skia.WPF.csproj
e2e/Uno/HelloWorld.Wasm/HelloWorld.Wasm.csproj
e2e/Uno/HelloWorld.Windows/HelloWorld.Windows.csproj
e2e/Uno/HelloWorld/HelloWorld.csproj
e2e/Uno/ModuleA/ModuleA.csproj
src/Directory.Build.props

Update Uno Check and publish net8 only version of Prism.Uno.WinUI

Update Uno to net8 and update Uno-Check

---

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs
tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs

Adds update to how we evaluate the UseModal Parameter and lookup logic for pushing modals
- fixes #2956
- none
n/a

Fixes issue pushing modals

---

.github/workflows/build_uno.yml
.github/workflows/ci.yml
.github/workflows/start-release.yml

Updates the skip options for Uno-Check

Update skip options for uno-check

---

Directory.Build.props
src/Directory.Build.targets

Updating Package Readme. Removing default Runtime Identifiers

Update Package ReadMe

---

src/Maui/Prism.Maui/Navigation/PageNavigationService.cs
tests/Maui/Prism.DryIoc.Maui.Tests/Fixtures/Navigation/NavigationTests.cs
tests/Maui/Prism.Maui.Tests/Prism.Maui.Tests.csproj

Resolves issue where a NullReferenceException is encountered in the Navigation which results in a failed Navigation
- fixes #3179

fix: null reference on TabbedPage evaluation

---

version.json

Bump to RC

---

.github/workflows/start-release.yml
Directory.Build.props

Adding Official Release flag for release notes. Fixing Release notes link.

Add OfficialRelease flag

---

.github/workflows/ci.yml

Update release trigger

---

.github/workflows/ci.yml
version.json

Update GitVersion public release spec

Update public release spec

---

Directory.Packages.props
global.json

Updating Uno & Prism Containers

Package updates

---

src/Maui/Prism.Maui/Navigation/IInitialize.cs
src/Maui/Prism.Maui/Navigation/IInitializeAsync.cs

Add Missing XML Docs To IInitialize and IInitializeAsync.
I only add missing XML Docs so I omitted tests.
- https://github.com/PrismLibrary/Prism/issues/1978
None.
None.

Add Missing XML Docs comments

---

version.json

Bump stable

---

.github/workflows/start-release.yml

Disables Uno.Check in the Release workflow

Disable Uno Check

---

Directory.Packages.props

Update Prism Containers
